#!/usr/bin/env python3
"""
Venture Hub Academy — static site generator.

Every page is assembled from the shared partials below, so the nav, footer,
CTA and hero can never drift apart between pages. Edit this file, then run:

    python3 tools/build_site.py

...and the .html files at the repo root are rewritten. Do not hand-edit the
generated pages: the next build overwrites them.

Design System v2.0 "Venture Energy" — Black / White / Purple / Sharp Purple.
"""
import hashlib, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://academy.venturehub.tech/"

# --- navigation: the single source of truth for site structure -------------
NAV = [
    ("Accelerator",    "accelerator.html"),
    ("Venture Studio", "venture-studio.html"),
    ("Community",      "community.html"),
    ("Portfolio",      "portfolio.html"),
    ("About",          "about.html"),
]

# --- photography: only four images exist, so crops carry the variation -----
# (large file, small file, large width, large height, small width) - the widths
# are the real pixel widths, since srcset descriptors that lie make the browser
# pick the wrong file.
PHOTO = {
    "home-event":      ("assets/images/home-event-1920.jpg", "assets/images/home-event-960.jpg", 1920, 1280, 960),
    "about-photo":     ("assets/images/about-photo-1600.jpg", "assets/images/about-photo-800.jpg", 1600, 1066, 800),
    "demo-day":        ("assets/images/demo-day-1600.jpg", "assets/images/demo-day-800.jpg", 1066, 1600, 533),
    "community-photo": ("assets/images/community-photo-1600.jpg", "assets/images/community-photo-800.jpg", 1066, 1600, 533),
}

GENERATED = "<!-- Generated by tools/build_site.py - edit the generator, not this file. -->"


def asset(path):
    """Append a content hash to an asset URL.

    Without this the stylesheet keeps one URL forever, so a cache can serve an
    old copy against freshly generated HTML — which silently breaks styling
    (text coloured for a dark section on a light one, for instance)."""
    with open(os.path.join(ROOT, path), "rb") as f:
        return "%s?v=%s" % (path, hashlib.sha256(f.read()).hexdigest()[:8])


def head(title, desc, url, extra=""):
    css = asset("css/vha-v2.css")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
{GENERATED}
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<meta name="robots" content="index, follow">
<meta name="theme-color" content="#F7F7F2">
<meta property="og:type" content="website">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="{SITE}{url}">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="{SITE}{url}">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{css}">
{extra}</head>
<body>
<a class="skip" href="#main">Skip to content</a>
"""


def chrome(current):
    drawer_links = "\n".join(
        f'    <a class="dl" href="{href}"><b>{i:02d}</b>{label}</a>'
        for i, (label, href) in enumerate(NAV, start=1))
    rows = []
    for label, href in NAV:
        aria = ' aria-current="page"' if href == current else ""
        rows.append('      <a href="%s"%s>%s</a>' % (href, aria, label))
    nav_links = "\n".join(rows)
    return f"""
<div class="backdrop" data-backdrop></div>
<aside class="drawer" data-drawer aria-label="Menu">
  <div class="drawer__top">
    <a href="index.html" class="brand">
      <img src="assets/logo/vha-mark-white-256.png" alt="" aria-hidden="true" width="30" height="30">
      <span>Venture Hub Academy</span>
    </a>
    <button type="button" class="drawer__x" data-close-menu aria-label="Close menu">&times;</button>
  </div>
  <nav aria-label="Mobile">
{drawer_links}
    <a class="dl" href="apply.html"><b>{len(NAV)+1:02d}</b>Apply Now &rarr;</a>
  </nav>
</aside>

<nav class="nav" aria-label="Primary">
  <div class="nav__in">
    <a href="index.html" class="brand">
      <img src="assets/logo/vha-mark-black-256.png" alt="" aria-hidden="true" width="30" height="30">
      <span>Venture Hub Academy</span>
    </a>
    <div class="nav__links">
{nav_links}
    </div>
    <div class="nav__right">
      <a href="apply.html" class="btn btn--purple">Apply Now <i aria-hidden="true">&rarr;</i></a>
      <button type="button" class="burger" data-open-menu aria-label="Menu" aria-expanded="false">
        <span></span><span></span><span></span>
      </button>
    </div>
  </div>
</nav>

<main id="main">
"""


def hero(eyebrow, title, lede, cta1, cta2, photo, alt, obj, meta):
    big, small, w, h, sw = PHOTO[photo]
    second = (f'\n            <a href="{cta2[1]}" class="btn btn--ghost">{cta2[0]} '
              f'<i aria-hidden="true">&rarr;</i></a>') if cta2 else ""
    metas = "\n".join(f"        <span>{m}</span>" for m in meta)
    return f"""  <header class="hero hero--inner mode-energy">
    <div class="wrap">
      <div class="hero__grid">
        <div>
          <p class="eyebrow">{eyebrow}</p>
          <h1 class="d-xl hero__title" data-reveal>{title}</h1>
          <p class="body-l hero__sub" data-reveal data-delay="0.08">{lede}</p>
          <div class="hero__cta" data-reveal data-delay="0.14">
            <a href="{cta1[1]}" class="btn btn--sharp">{cta1[0]} <i aria-hidden="true">&rarr;</i></a>{second}
          </div>
        </div>
        <div class="hero__media" data-reveal data-delay="0.2">
          <img src="{big}" srcset="{small} {sw}w, {big} {w}w"
               sizes="(max-width: 980px) 100vw, 45vw" style="object-position:{obj}"
               alt="{alt}" width="{w}" height="{h}" fetchpriority="high">
          <div class="hero__coord meta">22.3193&deg; N / 114.1694&deg; E</div>
        </div>
      </div>
      <div class="hero__meta-row meta">
{metas}
      </div>
    </div>
  </header>
"""


MARQUEE = """
  <div class="marquee" aria-hidden="true">
    <div class="marquee__t" data-marquee>
      <div class="marquee__g" data-marquee-group>
        <span class="marquee__i">Hong Kong</span>
        <span class="marquee__i">Taiwan</span>
        <span class="marquee__i">Singapore</span>
        <span class="marquee__i">Japan</span>
        <span class="marquee__i">Thailand</span>
        <span class="marquee__i">Cambodia</span>
      </div>
    </div>
  </div>
"""

PROOF = """
  <section class="section mode-inst" aria-label="By the numbers">
    <div class="wrap">
      <div class="proof">
        <div class="proof__item" data-reveal>
          <div class="proof__n"><small>US$</small><span data-count="150">150</span>K</div>
          <div class="proof__l">Invested via SAFE</div>
        </div>
        <div class="proof__item" data-reveal data-delay="0.06">
          <div class="proof__n"><span data-count="10">10</span></div>
          <div class="proof__l">Companies per cohort</div>
        </div>
        <div class="proof__item" data-reveal data-delay="0.12">
          <div class="proof__n"><span data-count="6">6</span></div>
          <div class="proof__l">Months of execution</div>
        </div>
        <div class="proof__item" data-reveal data-delay="0.18">
          <div class="proof__n"><span data-count="6">6</span></div>
          <div class="proof__l">APAC markets</div>
        </div>
      </div>
    </div>
  </section>
"""

APAC = """
  <section class="section mode-inst" id="apac">
    <div class="wrap">
      <div class="apac">
        <div>
          <p class="eyebrow">APAC network</p>
          <div class="apac__big" data-reveal aria-hidden="true">06</div>
          <h2 class="d-m" data-reveal style="margin-top:12px">One program.<br>Six markets.</h2>
          <ul class="markets" data-reveal data-delay="0.1">
            <li><b>HK</b>Hong Kong<span>22.32&deg; N</span></li>
            <li><b>TW</b>Taiwan<span>23.70&deg; N</span></li>
            <li><b>SG</b>Singapore<span>1.29&deg; N</span></li>
            <li><b>JP</b>Japan<span>35.68&deg; N</span></li>
            <li><b>TH</b>Thailand<span>13.75&deg; N</span></li>
            <li><b>KH</b>Cambodia<span>11.55&deg; N</span></li>
          </ul>
        </div>
        <div class="map" data-reveal data-delay="0.12">
          <canvas data-apac-map role="img"
                  aria-label="Network map of Venture Hub Academy's six APAC markets: Hong Kong, Taiwan, Singapore, Japan, Thailand and Cambodia."></canvas>
        </div>
      </div>
    </div>
  </section>
"""


def cta(title="Ready to build<br>what's next?"):
    return f"""
  <section class="cta-field">
    <div class="wrap">
      <h2 class="d-l" data-reveal>{title}</h2>
      <div class="row" data-reveal data-delay="0.08">
        <a href="apply.html" class="btn btn--dark">Apply Now <i aria-hidden="true">&rarr;</i></a>
        <a href="community.html" class="btn btn--ghost">Join the Community <i aria-hidden="true">&rarr;</i></a>
      </div>
    </div>
  </section>
"""


def footer():
    net = asset("js/vha-network.js")
    main = asset("js/vha-v2.js")
    explore = "\n".join(f'          <li><a href="{href}">{label}</a></li>' for label, href in NAV)
    return f"""</main>

<footer class="foot">
  <div class="wrap">
    <div class="foot__g">
      <div>
        <div class="foot__brand">
          <img src="assets/logo/vha-mark-white-256.png" alt="" aria-hidden="true" width="30" height="30">
          <span>Venture Hub Academy</span>
        </div>
        <p class="muted" style="font-size:15px">
          <a href="mailto:info@venturehub.tech">info@venturehub.tech</a><br>
          Supported by First Financial Holding
        </p>
      </div>
      <div>
        <h4>Explore</h4>
        <ul>
{explore}
          <li><a href="apply.html">Apply</a></li>
        </ul>
      </div>
      <div>
        <h4>Markets</h4>
        <ul>
          <li>Hong Kong</li><li>Taiwan</li><li>Singapore</li>
          <li>Japan</li><li>Thailand</li><li>Cambodia</li>
        </ul>
      </div>
      <div>
        <h4>Stay connected</h4>
        <p class="muted" style="font-size:15px">Join our newsletter for cohort news and events.</p>
        <form class="news" data-newsletter>
          <label class="vh" for="nl">Email address</label>
          <input type="email" id="nl" name="email" placeholder="Type your email" required>
          <button type="submit" aria-label="Subscribe">&rarr;</button>
        </form>
        <div class="social">
          <a href="https://www.linkedin.com" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">
            <svg width="17" height="17" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M4.98 3.5C4.98 4.88 3.87 6 2.5 6S0 4.88 0 3.5 1.12 1 2.5 1s2.48 1.12 2.48 2.5zM.5 8.25h4v15.25h-4zM8.5 8.25h3.84v2.08h.05c.53-1 1.83-2.08 3.77-2.08 4.03 0 4.78 2.66 4.78 6.11v9.14h-4v-8.1c0-1.93-.03-4.42-2.69-4.42-2.7 0-3.11 2.11-3.11 4.28v8.24h-4z"></path></svg>
          </a>
          <a href="https://x.com" target="_blank" rel="noopener noreferrer" aria-label="X (Twitter)">
            <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></svg>
          </a>
          <a href="https://www.instagram.com" target="_blank" rel="noopener noreferrer" aria-label="Instagram">
            <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><rect x="2.5" y="2.5" width="19" height="19" rx="5"></rect><circle cx="12" cy="12" r="4.3"></circle><circle cx="17.4" cy="6.6" r="1.1" fill="currentColor" stroke="none"></circle></svg>
          </a>
        </div>
      </div>
    </div>
    <div class="foot__b">
      <span data-year>&copy; 2026 Venture Hub Academy</span>
      <div><a href="#">Terms</a><a href="#">Privacy</a></div>
    </div>
  </div>
</footer>

<script src="{net}"></script>
<script src="{main}"></script>
"""


# d3 + topojson power the APAC network canvas. They are injected only into the
# pages that actually draw a map; without them VhaNetwork shows its text
# fallback instead of the map.
MAP_LIBS = """<script src="https://unpkg.com/d3@7.9.0/dist/d3.min.js" integrity="sha384-CjloA8y00+1SDAUkjs099PVfnY2KmDC2BZnws9kh8D/lX1s46w6EPhpXdqMfjK6i" crossorigin="anonymous" defer></script>
<script src="https://unpkg.com/topojson-client@3.1.0/dist/topojson-client.min.js" integrity="sha384-Ukv1p/xTma6P4/2bY5KzWBw+ydSpXmhCMtyciIQVDJ1RmOxtCYNMF1uXT9T63H67" crossorigin="anonymous" defer></script>
"""


def write(filename, title, desc, body, current, extra_head="", extra_js=""):
    if "data-apac-map" in body:
        extra_head = MAP_LIBS + extra_head
    url = "" if filename == "index.html" else filename   # canonical is the bare root
    html = (head(title, desc, url, extra_head) + chrome(current) + body
            + footer() + extra_js + "</body>\n</html>\n")
    with open(os.path.join(ROOT, filename), "w") as f:
        f.write(html)
    return filename, len(html)


# ==========================================================================
# Pages
# ==========================================================================

def page_home():
    body = hero(
        "AI Accelerator &middot; Venture Studio",
        "Backing execution-ready <em>AI founders</em> across Asia.",
        "Capital, compute, and market access for operators building real AI businesses.",
        ("Apply Now", "apply.html"), ("Explore VHA", "accelerator.html"),
        "home-event", "Founders and investors at a Venture Hub Academy session in Hong Kong.",
        "center 32%",
        ["APAC / HONG KONG / 2026", "COHORT 01 &mdash; APPLICATIONS OPEN", "HK &middot; TW &middot; SG &middot; JP &middot; TH &middot; KH"])
    body += PROOF + MARQUEE + """
  <!-- Why VHA -->
  <section class="section mode-energy">
    <div class="wrap">
      <div class="statement">
        <div>
          <p class="eyebrow eyebrow--orange">Why VHA</p>
          <h2 class="d-l statement__q" data-reveal>AI is moving fast.<br><b>Founders should too.</b></h2>
        </div>
        <div data-reveal data-delay="0.1">
          <p class="body-l muted">Most AI ventures stall not on technology, but on fragmented execution. We work hands-on with operators &mdash; refining models, launching in live markets, and building the traction that attracts serious capital.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Capital / Compute / Access -->
  <section class="section mode-purple" id="platform">
    <div class="wrap">
      <p class="eyebrow">The platform</p>
      <h2 class="d-m" data-reveal style="max-width:16ch;margin-bottom:56px">Everything you need to move faster.</h2>

      <div class="pillar" data-reveal>
        <div class="pillar__i">01</div>
        <div class="pillar__name">Capital</div>
        <div>
          <div class="pillar__v">US$150K</div>
          <p class="pillar__d">Initial capital to accelerate execution, invested via SAFE at the start of the program &mdash; with follow-on support into your next round.</p>
        </div>
      </div>
      <div class="pillar__arrow" aria-hidden="true">&darr;</div>

      <div class="pillar" data-reveal>
        <div class="pillar__i">02</div>
        <div class="pillar__name">Compute</div>
        <div>
          <div class="pillar__v">HPC / GPU</div>
          <p class="pillar__d">Infrastructure for building and testing. Immediate access to high-performance clusters for model training and deployment, from day one.</p>
        </div>
      </div>
      <div class="pillar__arrow" aria-hidden="true">&darr;</div>

      <div class="pillar" data-reveal>
        <div class="pillar__i">03</div>
        <div class="pillar__name">Access</div>
        <div>
          <div class="pillar__v">6 APAC Markets</div>
          <p class="pillar__d">A network designed for regional expansion &mdash; corporate and government pilots, regulatory support, and reference customers across six jurisdictions.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Program -->
  <section class="section mode-inst">
    <div class="wrap">
      <p class="eyebrow">The program</p>
      <h2 class="d-m" data-reveal style="max-width:18ch;margin-bottom:20px">From community to demo day.</h2>
      <p class="body-l muted" data-reveal style="max-width:52ch;margin-bottom:48px">Four stages. Six months. Built to produce traction, not coursework.</p>
      <div class="journey">
        <article class="stage" data-reveal>
          <div class="stage__n">01</div>
          <h3 class="stage__t">Community</h3>
          <p class="stage__d">Enter through the ecosystem. Meet founders, operators and builders before any commitment.</p>
          <span class="tag">Ongoing</span>
        </article>
        <article class="stage" data-reveal data-delay="0.06">
          <div class="stage__n">02</div>
          <h3 class="stage__t">Structured Program</h3>
          <p class="stage__d">Three months of focused execution &mdash; mentoring, corporate structuring and product strategy.</p>
          <span class="tag">3 months</span>
        </article>
        <article class="stage" data-reveal data-delay="0.12">
          <div class="stage__n">03</div>
          <h3 class="stage__t">APAC Sandbox</h3>
          <p class="stage__d">Three months of live market validation. Real pilots, real customers, real jurisdictions.</p>
          <span class="tag">3 months</span>
        </article>
        <article class="stage" data-reveal data-delay="0.18">
          <div class="stage__n">04</div>
          <h3 class="stage__t">Demo Day</h3>
          <p class="stage__d">Meet capital, partners and the ecosystem. Present live metrics, not projections.</p>
          <span class="tag">Cohort close</span>
        </article>
      </div>
      <p style="margin-top:40px"><a class="tlink" href="accelerator.html">See the full program <i aria-hidden="true">&rarr;</i></a></p>
    </div>
  </section>
""" + APAC + """
  <!-- Portfolio teaser -->
  <section class="section mode-energy">
    <div class="wrap">
      <div class="split">
        <div>
          <p class="eyebrow">Portfolio</p>
          <h2 class="d-m" data-reveal>A living collection<br>of companies.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <p class="body-l muted" style="margin-bottom:24px">Companies, founders, markets and outcomes from across the VHA network.</p>
          <a class="tlink" href="portfolio.html">See the portfolio <i aria-hidden="true">&rarr;</i></a>
        </div>
      </div>
    </div>
  </section>

  <!-- Ecosystem -->
  <section class="section mode-inst">
    <div class="wrap">
      <p class="eyebrow">Ecosystem</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:48px">Built with the people moving Asia forward.</h2>
      <div class="tiers">
        <article class="tier" data-reveal>
          <div class="tier__n">01</div>
          <h3 class="tier__t">Founders &amp; Operators</h3>
          <p class="tier__d">People who have built and scaled companies in these markets.</p>
          <div class="tier__foot muted">The network</div>
        </article>
        <article class="tier" data-reveal data-delay="0.06">
          <div class="tier__n">02</div>
          <h3 class="tier__t">Investors &amp; Corporates</h3>
          <p class="tier__d">Follow-on capital, pilot partners and first customers across the region.</p>
          <div class="tier__foot muted">The demand side</div>
        </article>
        <article class="tier tier--core" data-reveal data-delay="0.12">
          <div class="tier__n">03</div>
          <h3 class="tier__t">Researchers</h3>
          <p class="tier__d">Academic partners including HKU, HKUST and CUHK.</p>
          <div class="tier__foot">Institutional</div>
        </article>
      </div>
    </div>
  </section>
""" + cta()
    return write("index.html",
                 "Venture Hub Academy &mdash; Backing execution-ready AI founders across Asia",
                 "Capital, compute, and market access for operators building real AI businesses. US$150K, six months, six APAC markets.",
                 body, "index.html")


def page_accelerator():
    body = hero(
        "Accelerator",
        "A 6-month program<br>for <em>execution</em>.",
        "Three months of structured execution, then three months proving it in live APAC markets. US$150K via SAFE, small cohorts, and the compute to build on.",
        ("Apply Now", "apply.html"), ("See the phases", "#phases"),
        "demo-day", "Investors on stage during a Venture Hub Academy panel.", "center 22%",
        ["3 MONTHS STRUCTURED + 3 MONTHS SANDBOX", "US$150K VIA SAFE", "10 COMPANIES PER COHORT"])
    body += PROOF + MARQUEE + """
  <!-- Overview -->
  <section class="section mode-energy">
    <div class="wrap">
      <p class="eyebrow">Program overview</p>
      <h2 class="d-m" data-reveal style="max-width:18ch;margin-bottom:52px">How the program is built.</h2>
      <div class="numlist">
        <article class="numitem" data-reveal>
          <div class="numitem__n">01</div>
          <div>
            <h3 class="numitem__t">Six-month structure</h3>
            <p class="numitem__d">3-month Structured Program followed by a 3-month APAC Sandbox.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.06">
          <div class="numitem__n">02</div>
          <div>
            <h3 class="numitem__t">Small, focused cohorts</h3>
            <p class="numitem__d">Up to 10 companies per cohort, so every team gets real operator time.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.12">
          <div class="numitem__n">03</div>
          <div>
            <h3 class="numitem__t">Capital and compute</h3>
            <p class="numitem__d">US$150K via SAFE, plus GPU and compute resources from day one.</p>
          </div>
        </article>
      </div>
    </div>
  </section>

  <!-- Phases -->
  <section class="section mode-purple" id="phases">
    <div class="wrap">
      <p class="eyebrow">The two phases</p>
      <h2 class="d-m" data-reveal style="max-width:18ch;margin-bottom:44px">Build, then prove it.</h2>

      <div class="phase" data-reveal>
        <div>
          <span class="tag">Months 1&ndash;3</span>
          <h3 class="phase__t">Structured Program</h3>
        </div>
        <ul class="phase__list">
          <li>1-on-1 mentoring by experienced founders and operators.</li>
          <li>Corporate structuring support, research direction, and product strategy.</li>
          <li>Startup execution and scaling guidance.</li>
        </ul>
      </div>

      <div class="phase" data-reveal>
        <div>
          <span class="tag">Months 4&ndash;6</span>
          <h3 class="phase__t">APAC Sandbox</h3>
        </div>
        <ul class="phase__list">
          <li>Live customer validation across 6 markets: HK, TW, SG, JP, TH, Cambodia.</li>
          <li>Real revenue signals through live sales, partnerships, or LOIs.</li>
          <li>Accelerated traction-building ahead of fundraising.</li>
        </ul>
      </div>
    </div>
  </section>

  <!-- Compute -->
  <section class="section mode-energy">
    <div class="wrap">
      <div class="split">
        <div>
          <p class="eyebrow">Compute</p>
          <h2 class="d-m" data-reveal>HPC and GPU,<br>from day one.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <p class="body-l muted">Access to high-performance clusters for model training, evaluation and deployment &mdash; so infrastructure is never the reason a cohort company slows down.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Demo Day -->
  <section class="section mode-inst">
    <div class="wrap">
      <div class="split">
        <div>
          <p class="eyebrow eyebrow--orange">Demo Day</p>
          <h2 class="d-m" data-reveal>Present live metrics.<br>Raise on evidence.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <p class="body-l muted">Founders present live metrics to investors and community. Structured investor access and community-driven momentum.</p>
        </div>
      </div>
    </div>
  </section>
""" + APAC + cta()
    return write("accelerator.html",
                 "Accelerator &mdash; Venture Hub Academy",
                 "A 6-month program: 3-month Structured Program plus 3-month APAC Sandbox. US$150K via SAFE, small cohorts, GPU and compute resources.",
                 body, "accelerator.html")


def page_studio():
    body = hero(
        "Venture Studio",
        "From idea<br>to <em>company</em>.",
        "The accelerator backs founders. The studio builds with them &mdash; from thesis and incorporation through product, first customers and the raise.",
        ("Talk to the studio", "apply.html"), ("See the accelerator", "accelerator.html"),
        "about-photo", "Operators in discussion at a Venture Hub Academy session.", "center 40%",
        ["VENTURE STUDIO", "CO-BUILT FROM THESIS", "APAC / HONG KONG"])
    body += MARQUEE + """
  <!-- The difference -->
  <section class="section mode-energy">
    <div class="wrap">
      <p class="eyebrow">The difference</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:20px">Two ways we work.</h2>
      <p class="body-l muted" data-reveal style="max-width:54ch;margin-bottom:40px">Both routes lead to a company that can execute across Asia. They differ in where the idea starts and how much we build alongside you.</p>
      <div class="compare">
        <div class="compare__box">
          <div class="compare__label">Accelerator</div>
          <div class="compare__v">We back founders.</div>
          <p class="muted" style="margin-top:12px;font-size:15.5px">You bring the company and the commercial foundation. We bring capital, compute and market access for six months.</p>
        </div>
        <div class="compare__box compare__box--yes">
          <div class="compare__label">Venture Studio</div>
          <div class="compare__v">We build with founders.</div>
          <p class="muted" style="margin-top:12px;font-size:15.5px">We start from a thesis and build the company alongside you &mdash; entity, product, first customers and team.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- How the studio works -->
  <section class="section mode-purple">
    <div class="wrap">
      <p class="eyebrow">How the studio works</p>
      <h2 class="d-m" data-reveal style="max-width:18ch;margin-bottom:52px">Thesis to launch.</h2>
      <div class="numlist">
        <article class="numitem" data-reveal>
          <div class="numitem__n">01</div>
          <div>
            <h3 class="numitem__t">Thesis</h3>
            <p class="numitem__d">We identify where AI changes the economics of a sector in these markets, and what has to be true for a company to win there.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.06">
          <div class="numitem__n">02</div>
          <div>
            <h3 class="numitem__t">Build</h3>
            <p class="numitem__d">Prototype on VHA compute, tested against real operators before a company exists.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.12">
          <div class="numitem__n">03</div>
          <div>
            <h3 class="numitem__t">Incorporate</h3>
            <p class="numitem__d">Founding team, entity, cap table and jurisdiction &mdash; structured for the markets the company will sell into.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.18">
          <div class="numitem__n">04</div>
          <div>
            <h3 class="numitem__t">Scale</h3>
            <p class="numitem__d">First customers through the APAC Sandbox, then into the accelerator cohort and the raise.</p>
          </div>
        </article>
      </div>
    </div>
  </section>

  <!-- What we bring -->
  <section class="section mode-inst">
    <div class="wrap">
      <p class="eyebrow">What we bring</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:48px">Founding-team resources, on day zero.</h2>
      <div class="tiers">
        <article class="tier" data-reveal>
          <div class="tier__n">01</div>
          <h3 class="tier__t">Operators</h3>
          <p class="tier__d">People who have built in these markets, working on the company rather than advising it.</p>
          <div class="tier__foot muted">Hands-on</div>
        </article>
        <article class="tier" data-reveal data-delay="0.06">
          <div class="tier__n">02</div>
          <h3 class="tier__t">Infrastructure</h3>
          <p class="tier__d">HPC and GPU access for building and evaluating models before there is a budget for it.</p>
          <div class="tier__foot muted">HPC / GPU</div>
        </article>
        <article class="tier tier--core" data-reveal data-delay="0.12">
          <div class="tier__n">03</div>
          <h3 class="tier__t">Market access</h3>
          <p class="tier__d">Pilot partners across six jurisdictions, so the first customer conversation is not cold.</p>
          <div class="tier__foot">6 markets</div>
        </article>
      </div>
    </div>
  </section>

  <!-- Studio companies -->
  <section class="section mode-energy">
    <div class="wrap">
      <div class="split">
        <div>
          <p class="eyebrow">Studio companies</p>
          <h2 class="d-m" data-reveal>What we are building.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <span class="tag tag--pending" style="margin-bottom:18px">Awaiting content</span>
          <p class="body-l muted">Studio companies are announced once they are incorporated and in market. Details to follow.</p>
        </div>
      </div>
    </div>
  </section>
""" + cta("Have a thesis<br>worth building?")
    return write("venture-studio.html",
                 "Venture Studio &mdash; Venture Hub Academy",
                 "The accelerator backs founders. The venture studio builds with them - from thesis and incorporation through product, first customers and the raise.",
                 body, "venture-studio.html")


def _company(name, delay=""):
    d = f' data-delay="{delay}"' if delay else ""
    return f"""        <article class="co" data-reveal{d}>
          <span class="tag tag--pending">Awaiting content</span>
          <div class="co__n">{name}</div>
          <p class="co__d">One line on what the company builds and who it serves.</p>
          <dl class="co__m">
            <div><dt>Market</dt><dd>&mdash;</dd></div>
            <div><dt>Stage</dt><dd>&mdash;</dd></div>
          </dl>
        </article>"""


def page_portfolio():
    cards = "\n".join([_company("Company name"), _company("Company name", "0.06"),
                       _company("Company name", "0.12"), _company("Company name", "0.18"),
                       _company("Company name", "0.24"), _company("Company name", "0.3")])
    body = hero(
        "Portfolio",
        "A living collection<br>of <em>companies</em>.",
        "Companies, founders, markets and outcomes from across the VHA network. Backed with capital, compute and market access, then proven in live APAC markets.",
        ("Apply Now", "apply.html"), ("See the program", "accelerator.html"),
        "community-photo", "Founders and members at a Venture Hub Academy session.", "center 68%",
        ["COHORT 01", "6 APAC MARKETS", "PRE-SEED &mdash; SEED"])
    body += MARQUEE + f"""
  <!-- Companies -->
  <section class="section mode-inst" id="companies">
    <div class="wrap">
      <div class="split" style="margin-bottom:48px">
        <div>
          <p class="eyebrow">Companies</p>
          <h2 class="d-m" data-reveal>Cohort 01.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <p class="body-l muted">The first cohort is being selected now. Company profiles are published once each team is in market.</p>
        </div>
      </div>
      <div class="folio">
{cards}
      </div>
    </div>
  </section>

  <!-- Founder story -->
  <section class="section mode-energy">
    <div class="wrap">
      <div class="story">
        <div data-reveal>
          <img src="assets/images/about-photo-1600.jpg"
               srcset="assets/images/about-photo-800.jpg 800w, assets/images/about-photo-1600.jpg 1600w"
               sizes="(max-width: 900px) 100vw, 46vw"
               alt="Panel discussion with investors and operators at a Venture Hub Academy session."
               width="1600" height="1066" loading="lazy">
        </div>
        <div data-reveal data-delay="0.1">
          <p class="eyebrow">Founder stories</p>
          <blockquote class="story__q">&ldquo;We needed more than capital. We needed access.&rdquo;</blockquote>
          <p class="meta" style="margin-bottom:20px">FOUNDER / COMPANY / MARKET</p>
          <span class="tag tag--pending">Placeholder &mdash; awaiting a real founder quote</span>
        </div>
      </div>
    </div>
  </section>

  <!-- What backing looks like -->
  <section class="section mode-purple">
    <div class="wrap">
      <p class="eyebrow">What backing looks like</p>
      <h2 class="d-m" data-reveal style="max-width:18ch;margin-bottom:52px">Every company gets the same three things.</h2>
      <div class="numlist">
        <article class="numitem" data-reveal>
          <div class="numitem__n">01</div>
          <div>
            <h3 class="numitem__t">US$150K via SAFE</h3>
            <p class="numitem__d">Invested at the start of the program, with follow-on support into the next round.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.06">
          <div class="numitem__n">02</div>
          <div>
            <h3 class="numitem__t">HPC and GPU access</h3>
            <p class="numitem__d">Compute for training, evaluation and deployment from day one.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.12">
          <div class="numitem__n">03</div>
          <div>
            <h3 class="numitem__t">Six markets</h3>
            <p class="numitem__d">Pilots, partners and reference customers across Hong Kong, Taiwan, Singapore, Japan, Thailand and Cambodia.</p>
          </div>
        </article>
      </div>
    </div>
  </section>
""" + cta("Want to be<br>in cohort 01?")
    return write("portfolio.html",
                 "Portfolio &mdash; Venture Hub Academy",
                 "Companies, founders, markets and outcomes from across the Venture Hub Academy network.",
                 body, "portfolio.html")


def page_community():
    body = hero(
        "Community",
        "From open forum<br>to <em>core cohort</em>.",
        "Every cohort starts in the community. It is the open door into the network &mdash; founders, operators and builders, meeting before any commitment is made.",
        ("Join the Community", "apply.html"), ("See the program", "accelerator.html"),
        "home-event", "Founders networking at a Venture Hub Academy event in Hong Kong.", "center 30%",
        ["OPEN FORUM", "MEMBERS", "CORE COHORT"])
    body += MARQUEE + """
  <!-- Tiers -->
  <section class="section mode-inst">
    <div class="wrap">
      <p class="eyebrow">How the community works</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:20px">Three ways in.</h2>
      <p class="body-l muted" data-reveal style="max-width:52ch;margin-bottom:48px">The community narrows as commitment deepens &mdash; from an open forum, to members, to the funded cohort.</p>
      <div class="tiers">
        <article class="tier" data-reveal>
          <div class="tier__n">01</div>
          <h3 class="tier__t">Open Forum</h3>
          <p class="tier__d">Open network, discussing startup ideas, early intent surfacing.</p>
          <div class="tier__foot muted">Open to all</div>
        </article>
        <article class="tier" data-reveal data-delay="0.06">
          <div class="tier__n">02</div>
          <h3 class="tier__t">Members</h3>
          <p class="tier__d">Alumni and shortlisted participants, access to exclusive events.</p>
          <div class="tier__foot muted">By shortlist</div>
        </article>
        <article class="tier tier--core" data-reveal data-delay="0.12">
          <div class="tier__n">03</div>
          <h3 class="tier__t">Core Cohort</h3>
          <p class="tier__d">10+ selectively chosen teams, direct funding and network access.</p>
          <div class="tier__foot">Funded &middot; US$150K</div>
        </article>
      </div>
    </div>
  </section>

  <!-- Activity -->
  <section class="section mode-energy">
    <div class="wrap">
      <p class="eyebrow">Activity</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:48px">Something is always happening.</h2>
      <div class="collage" data-reveal>
        <figure class="c-wide">
          <img src="assets/images/home-event-1920.jpg" alt="Founders networking at a Venture Hub Academy event." width="1920" height="1280" loading="lazy">
          <figcaption>Community night &middot; Hong Kong</figcaption>
        </figure>
        <figure class="c-tall">
          <img src="assets/images/demo-day-800.jpg" alt="Panel session with investors at a Venture Hub Academy event." width="533" height="800" loading="lazy">
          <figcaption>Investor panel</figcaption>
        </figure>
        <figure>
          <img src="assets/images/community-photo-800.jpg" alt="Audience at a Venture Hub Academy session." width="533" height="800" loading="lazy">
          <figcaption>Founder session</figcaption>
        </figure>
        <figure>
          <img src="assets/images/about-photo-800.jpg" alt="Operators in discussion at a Venture Hub Academy session." width="800" height="533" loading="lazy">
          <figcaption>Operator discussion</figcaption>
        </figure>
      </div>
    </div>
  </section>

  <!-- Events -->
  <section class="section mode-inst" id="events">
    <div class="wrap">
      <p class="eyebrow eyebrow--orange">Up next</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:20px">Events across the network.</h2>
      <span class="tag tag--pending" data-reveal style="margin-bottom:36px">Schedule to be confirmed</span>
      <div class="event-list" style="margin-top:8px">
        <div class="event-row">
          <div class="meta">DATE TBC / HKG</div>
          <div><div class="event-row__t">Demo Day</div></div>
          <div class="meta">HONG KONG</div>
        </div>
        <div class="event-row">
          <div class="meta">DATE TBC / HKG</div>
          <div><div class="event-row__t">Founder Dinner</div></div>
          <div class="meta">HONG KONG</div>
        </div>
        <div class="event-row">
          <div class="meta">DATE TBC / SIN</div>
          <div><div class="event-row__t">AI Infrastructure Session</div></div>
          <div class="meta">SINGAPORE</div>
        </div>
        <div class="event-row">
          <div class="meta">DATE TBC / TYO</div>
          <div><div class="event-row__t">Investor Roundtable</div></div>
          <div class="meta">TOKYO</div>
        </div>
      </div>
    </div>
  </section>
""" + cta("Ready to join<br>the network?")
    return write("community.html",
                 "Community &mdash; Venture Hub Academy",
                 "From Open Forum to Core Cohort - join the Venture Hub Academy community of founders, operators, and builders across Asia.",
                 body, "community.html")


def page_about():
    body = hero(
        "About",
        "Domain expertise,<br>turned into <em>ventures</em>.",
        "Venture Hub Academy builds and scales AI-driven businesses by partnering with experienced operators &mdash; transforming domain expertise into high-growth, technology-enabled ventures.",
        ("Apply Now", "apply.html"), ("See the accelerator", "accelerator.html"),
        "about-photo", "A Venture Hub Academy panel discussion.", "center 40%",
        ["APAC / HONG KONG / 2026", "ACCELERATOR &middot; VENTURE STUDIO", "BACKED BY FIRST FINANCIAL HOLDING"])
    body += MARQUEE + """
  <!-- Who we back -->
  <section class="section mode-inst">
    <div class="wrap">
      <div class="split">
        <div>
          <p class="eyebrow">Who we back</p>
          <h2 class="d-m" data-reveal>Experienced operators,<br>not idea-stage<br>first-timers.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <p class="body-l muted">Venture Hub Academy prioritizes experienced operators over first-time, idea-stage founders. We look for teams with an established commercial foundation who are ready to execute &mdash; not validate an idea from zero.</p>
          <div class="compare">
            <div class="compare__box">
              <div class="compare__label">Not our fit</div>
              <div class="compare__v">Idea-stage first-timers</div>
            </div>
            <div class="compare__box compare__box--yes">
              <div class="compare__label">Our fit</div>
              <div class="compare__v">Experienced operators</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Selection criteria -->
  <section class="section mode-energy">
    <div class="wrap">
      <p class="eyebrow">Selection criteria</p>
      <h2 class="d-m" data-reveal style="max-width:16ch;margin-bottom:52px">What we look for.</h2>
      <div class="numlist">
        <article class="numitem" data-reveal>
          <div class="numitem__n">01</div>
          <div>
            <h3 class="numitem__t">Team quality</h3>
            <p class="numitem__d">Quality of team / visionaries of an established business.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.06">
          <div class="numitem__n">02</div>
          <div>
            <h3 class="numitem__t">Unique technology</h3>
            <p class="numitem__d">Potentially groundbreaking product or service based on unique technologies.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.12">
          <div class="numitem__n">03</div>
          <div>
            <h3 class="numitem__t">Commercial proposition</h3>
            <p class="numitem__d">Clear, proven commercial proposition with global opportunities.</p>
          </div>
        </article>
      </div>
    </div>
  </section>

  <!-- Two engines -->
  <section class="section mode-inst">
    <div class="wrap">
      <p class="eyebrow">Two engines</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:20px">Back founders. Build companies.</h2>
      <p class="body-l muted" data-reveal style="max-width:54ch;margin-bottom:40px">VHA runs an accelerator and a venture studio from the same platform of capital, compute and market access.</p>
      <div class="compare">
        <div class="compare__box">
          <div class="compare__label">Accelerator</div>
          <div class="compare__v">We back founders.</div>
          <p class="muted" style="margin-top:12px;font-size:15.5px">A 6-month program for execution-ready teams.</p>
          <p style="margin-top:16px"><a class="tlink" href="accelerator.html">See the program <i aria-hidden="true">&rarr;</i></a></p>
        </div>
        <div class="compare__box compare__box--yes">
          <div class="compare__label">Venture Studio</div>
          <div class="compare__v">We build with founders.</div>
          <p class="muted" style="margin-top:12px;font-size:15.5px">Companies co-built from thesis to launch.</p>
          <p style="margin-top:16px"><a class="tlink" href="venture-studio.html">See the studio <i aria-hidden="true">&rarr;</i></a></p>
        </div>
      </div>
    </div>
  </section>

  <!-- Backing -->
  <section class="section mode-purple">
    <div class="wrap">
      <div class="split">
        <div>
          <p class="eyebrow">Institutional backing</p>
          <h2 class="d-m" data-reveal>Backed by institutions.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <div class="backing">
            <div class="backing__box">
              <div class="backing__label">Financial</div>
              <div class="backing__v">First Financial Holding</div>
            </div>
            <div class="backing__box">
              <div class="backing__label">Academic</div>
              <div class="backing__v">HKU &middot; HKUST &middot; CUHK</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
""" + cta()
    return write("about.html",
                 "About &mdash; Venture Hub Academy",
                 "Venture Hub Academy builds and scales AI-driven businesses by partnering with experienced operators across Asia.",
                 body, "about.html")


APPLY_FORM = open(os.path.join(ROOT, "tools", "apply-form.html")).read() if os.path.exists(
    os.path.join(ROOT, "tools", "apply-form.html")) else ""


def page_apply():
    body = hero(
        "Apply",
        "Fifteen minutes.<br>Read by a <em>partner</em>.",
        "Applications are reviewed on a rolling basis. We respond to every application within 14 days, either way.",
        ("Start application", "#apply-form"), ("See the program", "accelerator.html"),
        "demo-day", "Investors on stage during a Venture Hub Academy panel.", "center 22%",
        ["ROLLING BASIS", "RESPONSE WITHIN 14 DAYS", "COHORT 01 &mdash; APPLICATIONS OPEN"])
    body += MARQUEE + """
  <!-- Process -->
  <section class="section mode-inst">
    <div class="wrap">
      <p class="eyebrow">The process</p>
      <h2 class="d-m" data-reveal style="max-width:18ch;margin-bottom:52px">Three steps.</h2>
      <div class="numlist">
        <article class="numitem" data-reveal>
          <div class="numitem__n">01</div>
          <div>
            <h3 class="numitem__t">Application</h3>
            <p class="numitem__d">This form. Reviewed on a rolling basis &mdash; we respond to every application within 14 days.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.06">
          <div class="numitem__n">02</div>
          <div>
            <h3 class="numitem__t">Partner interviews</h3>
            <p class="numitem__d">Two conversations, product-deep. With partners, not associates.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.12">
          <div class="numitem__n">03</div>
          <div>
            <h3 class="numitem__t">Offer</h3>
            <p class="numitem__d">US$150K via SAFE on standard terms, and a start date for the next cohort.</p>
          </div>
        </article>
      </div>
    </div>
  </section>
""" + APPLY_FORM
    return write("apply.html",
                 "Apply &mdash; Venture Hub Academy",
                 "Fifteen minutes. Read by a partner. Apply to the Venture Hub Academy accelerator.",
                 body, "apply.html",
                 extra_js='<script src="%s"></script>\n' % asset("js/vha-apply.js"))


def build_sitemap(pages):
    prio = {"index.html": ("weekly", "1.0"), "apply.html": ("monthly", "0.9"),
            "accelerator.html": ("monthly", "0.9"), "venture-studio.html": ("monthly", "0.8"),
            "portfolio.html": ("monthly", "0.8"), "community.html": ("monthly", "0.8"),
            "about.html": ("monthly", "0.7")}
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">', '']
    for p in pages:
        cf, pr = prio.get(p, ("monthly", "0.7"))
        loc = SITE if p == "index.html" else SITE + p
        out += ['  <url>', f'    <loc>{loc}</loc>',
                f'    <changefreq>{cf}</changefreq>', f'    <priority>{pr}</priority>', '  </url>', '']
    out.append('</urlset>')
    with open(os.path.join(ROOT, "sitemap.xml"), "w") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    built = [page_home(), page_accelerator(), page_studio(), page_portfolio(),
             page_community(), page_about(), page_apply()]
    for name, size in built:
        print(f"  {name:22} {size:>7,} bytes")
    build_sitemap([n for n, _ in built])
    print(f"  {'sitemap.xml':22} rebuilt")
    print(f"\n{len(built)} pages built.")
