#!/usr/bin/env python3
"""
Venture Hub Academy — static site generator.

Every page is assembled from the shared partials below, so the nav, footer,
CTA and hero can never drift apart between pages. Edit this file, then run:

    python3 tools/build_site.py

...and the .html files at the repo root are rewritten. Do not hand-edit the
generated pages: the next build overwrites them.

Design System v2.0 "Venture Energy" — Black / White / Purple / Sharp Purple.
"""
import glob, hashlib, json, os, re, sys
from html import escape, unescape
from html.parser import HTMLParser

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import blog
SITE = "https://academy.venturehub.tech/"

# --- navigation: the single source of truth for site structure -------------
NAV = [
    ("Accelerator",    "accelerator.html", "nav.acc"),
    ("Community",      "community.html",   "nav.com"),
    ("About",          "about.html",       "nav.about"),
    ("Blog",           "blog/",            "nav.blog"),
]

# --- photography: all from the Venture Showcase at HKU, 23 May 2026 ---------
# (large file, small file, large width, large height, small width) - the widths
# are the real pixel widths, since srcset descriptors that lie make the browser
# pick the wrong file.
PHOTO = {
    "home-event":      ("assets/images/home-event-1920.jpg", "assets/images/home-event-960.jpg", 1920, 1280, 960),
    "about-photo":     ("assets/images/about-photo-1600.jpg", "assets/images/about-photo-800.jpg", 1600, 1066, 800),
    "demo-day":        ("assets/images/demo-day-1600.jpg", "assets/images/demo-day-800.jpg", 1066, 1600, 533),
    "community-photo": ("assets/images/community-photo-1600.jpg", "assets/images/community-photo-800.jpg", 1066, 1600, 533),
    "pitch-results":   ("assets/images/pitch-results-1600.jpg", "assets/images/pitch-results-800.jpg", 1066, 1599, 533),
    "vc-challenge":    ("assets/images/vc-challenge-1600.jpg", "assets/images/vc-challenge-800.jpg", 1066, 1599, 533),
    "audience-laugh":  ("assets/images/audience-laugh-1600.jpg", "assets/images/audience-laugh-800.jpg", 1066, 1599, 533),
    "blog-hero":       ("assets/images/blog-hero-1600.jpg", "assets/images/blog-hero-800.jpg", 1066, 1599, 533),
}

GENERATED = "<!-- Generated by tools/build_site.py - edit the generator, not this file. -->"


def asset(path):
    """Append a content hash to an asset URL.

    Without this the stylesheet keeps one URL forever, so a cache can serve an
    old copy against freshly generated HTML — which silently breaks styling
    (text coloured for a dark section on a light one, for instance)."""
    with open(os.path.join(ROOT, path), "rb") as f:
        return "%s?v=%s" % (path, hashlib.sha256(f.read()).hexdigest()[:8])


def head(title, desc, url, extra=""):
    css = asset("css/vha-v2.css")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
{GENERATED}
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<meta name="robots" content="index, follow">
<meta name="theme-color" content="#F7F7F2">
<meta property="og:type" content="website">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="{SITE}{url}">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="{SITE}{url}">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&family=Noto+Sans+SC:wght@400;500;700&family=Noto+Sans+TC:wght@400;500;700&family=Noto+Sans+JP:wght@400;500;700&family=Noto+Sans+Thai:wght@400;500;700&family=Noto+Sans+Khmer:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{css}">
{extra}</head>
<body>
<a class="skip" href="#main" data-i18n="chrome.skipToContent">Skip to content</a>
"""


def chrome(current):
    """Nav, mobile drawer and language switcher.

    Internal links carry data-internal so i18n.js can re-append ?lang= to them:
    without it, following any link silently drops the visitor back to English.
    The switcher itself is built at runtime from i18n.js's LANGS list, so the
    language list lives in one place rather than being duplicated per page."""
    drawer_links = "\n".join(
        f'    <a class="dl" href="{href}" data-internal><b>{i:02d}</b><span data-i18n="{key}">{label}</span></a>'
        for i, (label, href, key) in enumerate(NAV, start=1))
    rows = []
    for label, href, key in NAV:
        aria = ' aria-current="page"' if href == current else ""
        rows.append('      <a href="%s"%s data-internal data-i18n="%s">%s</a>' % (href, aria, key, label))
    nav_links = "\n".join(rows)
    return f"""
<div class="backdrop" data-backdrop></div>
<aside class="drawer" data-drawer aria-label="Menu" data-i18n-attr="aria-label:chrome.menuLabel">
  <div class="drawer__top">
    <a href="index.html" class="brand" data-internal>
      <img src="assets/logo/vha-mark-white-256.png" alt="" aria-hidden="true" width="30" height="30">
      <span>Venture Hub Academy</span>
    </a>
    <button type="button" class="drawer__x" data-close-menu aria-label="Close menu"
            data-i18n-attr="aria-label:chrome.closeMenu">&times;</button>
  </div>
  <nav aria-label="Mobile">
{drawer_links}
    <a class="dl" href="apply.html" data-internal><b>{len(NAV)+1:02d}</b><span data-i18n="nav.applyNow">Apply Now</span> &rarr;</a>
  </nav>
  <div class="drawer__langs">
    <div class="drawer__langs-label" data-i18n="chrome.languageLabel">Language</div>
    <div class="drawer__lang-list" data-drawer-lang-list></div>
  </div>
</aside>

<nav class="nav" aria-label="Primary">
  <div class="nav__in">
    <a href="index.html" class="brand" data-internal>
      <img src="assets/logo/vha-mark-black-256.png" alt="" aria-hidden="true" width="30" height="30">
      <span>Venture Hub Academy</span>
    </a>
    <div class="nav__links">
{nav_links}
    </div>
    <div class="nav__right">
      <div class="lang-switch" data-lang-switch data-open="false">
        <button type="button" class="lang-switch__button" data-lang-trigger
                aria-haspopup="listbox" aria-expanded="false" aria-label="Language"
                data-i18n-attr="aria-label:chrome.languageLabel">
          <span data-lang-label>EN</span><span class="lang-switch__caret" aria-hidden="true">&#9662;</span>
        </button>
        <div class="lang-switch__menu" data-lang-menu></div>
      </div>
      <a href="apply.html" class="btn btn--purple" data-internal><span data-i18n="nav.applyNow">Apply Now</span> <i aria-hidden="true">&rarr;</i></a>
      <button type="button" class="burger" data-open-menu aria-label="Menu" aria-expanded="false"
              data-i18n-attr="aria-label:chrome.menuLabel">
        <span></span><span></span><span></span>
      </button>
    </div>
  </div>
</nav>

<main id="main">
"""


def hero(k, eyebrow, title, lede, cta1, cta2, photo, alt, obj, meta):
    """The shared hero. `k` is the page's locale prefix, e.g. "home".

    Headline and lede bind through data-i18n-html, not data-i18n: both carry
    markup the design depends on - the <em> highlighter band and the <br>
    breaks that set the line rhythm - and textContent would render those as
    literal angle brackets. Translations must keep the same tags."""
    big, small, w, h, sw = PHOTO[photo]
    second = (f'\n            <a href="{cta2[1]}" class="btn btn--ghost" data-internal>'
              f'<span data-i18n="{k}.hero.cta2">{cta2[0]}</span> '
              f'<i aria-hidden="true">&rarr;</i></a>') if cta2 else ""
    metas = "\n".join(f'        <span data-i18n="{k}.hero.meta.{i}">{m}</span>'
                      for i, m in enumerate(meta))
    return f"""  <header class="hero hero--inner mode-energy">
    <div class="wrap">
      <div class="hero__grid">
        <div>
          <p class="eyebrow" data-i18n="{k}.hero.eyebrow">{eyebrow}</p>
          <h1 class="d-xl hero__title" data-reveal data-i18n-html="{k}.hero.title">{title}</h1>
          <p class="body-l hero__sub" data-reveal data-delay="0.08" data-i18n-html="{k}.hero.lede">{lede}</p>
          <div class="hero__cta" data-reveal data-delay="0.14">
            <a href="{cta1[1]}" class="btn btn--sharp" data-internal><span data-i18n="{k}.hero.cta1">{cta1[0]}</span> <i aria-hidden="true">&rarr;</i></a>{second}
          </div>
        </div>
        <div class="hero__media" data-reveal data-delay="0.2">
          <img src="{big}" srcset="{small} {sw}w, {big} {w}w"
               sizes="(max-width: 980px) 100vw, 45vw" style="object-position:{obj}"
               alt="{alt}" width="{w}" height="{h}" fetchpriority="high"
               data-i18n-attr="alt:{k}.hero.alt">
          <div class="hero__coord meta">22.3193&deg; N / 114.1694&deg; E</div>
        </div>
      </div>
      <div class="hero__meta-row meta">
{metas}
      </div>
    </div>
  </header>
"""


MARQUEE = """
  <div class="marquee" aria-hidden="true">
    <div class="marquee__t" data-marquee>
      <div class="marquee__g" data-marquee-group>
        <span class="marquee__i" data-i18n="markets.hk">Hong Kong</span>
        <span class="marquee__i" data-i18n="markets.tw">Taiwan</span>
        <span class="marquee__i" data-i18n="markets.sg">Singapore</span>
        <span class="marquee__i" data-i18n="markets.jp">Japan</span>
        <span class="marquee__i" data-i18n="markets.th">Thailand</span>
        <span class="marquee__i" data-i18n="markets.kh">Cambodia</span>
      </div>
    </div>
  </div>
"""

# The stat icons are inline line drawings in the same stroke style as the
# footer's social icons; PROOF is shared, so every page that shows the stats
# shows the same four.
PROOF = """
  <section class="section mode-inst proof-section" aria-label="By the numbers">
    <div class="wrap">
      <div class="proof">
        <div class="proof__item" data-reveal>
          <svg class="proof__i" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="2.5" y="6" width="19" height="12" rx="2"></rect><circle cx="12" cy="12" r="2.6"></circle><path d="M6 12h.01M18 12h.01"></path></svg>
          <div class="proof__b">
            <div class="proof__n"><small>US$</small><span data-count="150">150</span>K</div>
            <div class="proof__l" data-i18n="proof.safe">Invested via SAFE</div>
          </div>
        </div>
        <div class="proof__item" data-reveal data-delay="0.06">
          <svg class="proof__i" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="3" width="7.5" height="7.5" rx="1.5"></rect><rect x="13.5" y="3" width="7.5" height="7.5" rx="1.5"></rect><rect x="3" y="13.5" width="7.5" height="7.5" rx="1.5"></rect><rect x="13.5" y="13.5" width="7.5" height="7.5" rx="1.5"></rect></svg>
          <div class="proof__b">
            <div class="proof__n"><span data-count="10">10</span></div>
            <div class="proof__l" data-i18n="proof.companies">Companies per cohort</div>
          </div>
        </div>
        <div class="proof__item" data-reveal data-delay="0.12">
          <svg class="proof__i" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4.5" width="18" height="16.5" rx="2"></rect><path d="M3 9.5h18M8 2.5v4M16 2.5v4M7.5 13.5h.01M12 13.5h.01M16.5 13.5h.01M7.5 17h.01M12 17h.01"></path></svg>
          <div class="proof__b">
            <div class="proof__n"><span data-count="6">6</span></div>
            <div class="proof__l" data-i18n="proof.months">Months of execution</div>
          </div>
        </div>
        <div class="proof__item" data-reveal data-delay="0.18">
          <svg class="proof__i" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"></circle><ellipse cx="12" cy="12" rx="4" ry="9"></ellipse><path d="M3 12h18"></path></svg>
          <div class="proof__b">
            <div class="proof__n"><span data-count="6">6</span></div>
            <div class="proof__l" data-i18n="proof.markets">APAC markets</div>
          </div>
        </div>
      </div>
    </div>
  </section>
"""

APAC = """
  <section class="section mode-inst" id="apac">
    <div class="wrap">
      <div class="apac">
        <div>
          <p class="eyebrow" data-i18n="apac.eyebrow">APAC network</p>
          <div class="apac__big" data-reveal aria-hidden="true">06</div>
          <h2 class="d-m" data-reveal style="margin-top:12px" data-i18n-html="apac.title">One program.<br>Six markets.</h2>
          <ul class="markets" data-reveal data-delay="0.1">
            <li><b>HK</b><span data-i18n="markets.hk">Hong Kong</span><span>22.32&deg; N</span></li>
            <li><b>TW</b><span data-i18n="markets.tw">Taiwan</span><span>23.70&deg; N</span></li>
            <li><b>SG</b><span data-i18n="markets.sg">Singapore</span><span>1.29&deg; N</span></li>
            <li><b>JP</b><span data-i18n="markets.jp">Japan</span><span>35.68&deg; N</span></li>
            <li><b>TH</b><span data-i18n="markets.th">Thailand</span><span>13.75&deg; N</span></li>
            <li><b>KH</b><span data-i18n="markets.kh">Cambodia</span><span>11.55&deg; N</span></li>
          </ul>
        </div>
        <div class="map" data-reveal data-delay="0.12">
          <canvas data-apac-map role="img"
                  aria-label="Network map of Venture Hub Academy's six APAC markets: Hong Kong, Taiwan, Singapore, Japan, Thailand and Cambodia."
                  data-map-unavailable="Interactive map unavailable. Markets: Hong Kong, Taiwan, Singapore, Japan, Thailand, Cambodia."
                  data-i18n-attr="aria-label:apac.mapLabel;data-map-unavailable:chrome.mapUnavailable"></canvas>
        </div>
      </div>
    </div>
  </section>
"""


def cta(title="Ready to build<br>what's next?", k="cta.title"):
    """Closing CTA. `k` lets a page carry its own headline; the two buttons
    are identical everywhere, so they share one pair of keys."""
    return f"""
  <section class="cta-field">
    <div class="wrap">
      <h2 class="d-l" data-reveal data-i18n-html="{k}">{title}</h2>
      <div class="row" data-reveal data-delay="0.08">
        <a href="apply.html" class="btn btn--dark" data-internal><span data-i18n="nav.applyNow">Apply Now</span> <i aria-hidden="true">&rarr;</i></a>
        <a href="community.html" class="btn btn--ghost" data-internal><span data-i18n="cta.join">Join the Community</span> <i aria-hidden="true">&rarr;</i></a>
      </div>
    </div>
  </section>
"""


def footer():
    i18n = asset("js/i18n.js")
    net = asset("js/vha-network.js")
    main = asset("js/vha-v2.js")
    explore = "\n".join(
        f'          <li><a href="{href}" data-internal data-i18n="{key}">{label}</a></li>'
        for label, href, key in NAV)
    return f"""</main>

<footer class="foot">
  <div class="wrap">
    <div class="foot__g">
      <div>
        <div class="foot__brand">
          <img src="assets/logo/vha-mark-white-256.png" alt="" aria-hidden="true" width="30" height="30">
          <span>Venture Hub Academy</span>
        </div>
        <p class="muted" style="font-size:15px">
          <a href="mailto:info@venturehub.tech">info@venturehub.tech</a><br>
          <span data-i18n="footer.supported">Supported by First Financial Holding</span>
        </p>
      </div>
      <div>
        <h4 data-i18n="footer.exploreH">Explore</h4>
        <ul>
{explore}
          <li><a href="apply.html" data-internal data-i18n="nav.apply">Apply</a></li>
        </ul>
      </div>
      <div>
        <h4 data-i18n="footer.marketsH">Markets</h4>
        <ul>
          <li data-i18n="markets.hk">Hong Kong</li><li data-i18n="markets.tw">Taiwan</li><li data-i18n="markets.sg">Singapore</li>
          <li data-i18n="markets.jp">Japan</li><li data-i18n="markets.th">Thailand</li><li data-i18n="markets.kh">Cambodia</li>
        </ul>
      </div>
      <div>
        <h4 data-i18n="footer.stayH">Stay connected</h4>
        <p class="muted" style="font-size:15px" data-i18n="footer.stayP">Join our newsletter for cohort news and events.</p>
        <form class="news" data-newsletter>
          <label class="vh" for="nl" data-i18n="footer.emailLabel">Email address</label>
          <input type="email" id="nl" name="email" placeholder="Type your email" required
                 data-i18n-attr="placeholder:footer.emailPh">
          <button type="submit" aria-label="Subscribe" data-i18n-attr="aria-label:footer.subscribe">&rarr;</button>
        </form>
        <div class="social">
          <a href="https://www.linkedin.com" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">
            <svg width="17" height="17" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M4.98 3.5C4.98 4.88 3.87 6 2.5 6S0 4.88 0 3.5 1.12 1 2.5 1s2.48 1.12 2.48 2.5zM.5 8.25h4v15.25h-4zM8.5 8.25h3.84v2.08h.05c.53-1 1.83-2.08 3.77-2.08 4.03 0 4.78 2.66 4.78 6.11v9.14h-4v-8.1c0-1.93-.03-4.42-2.69-4.42-2.7 0-3.11 2.11-3.11 4.28v8.24h-4z"></path></svg>
          </a>
          <a href="https://x.com" target="_blank" rel="noopener noreferrer" aria-label="X (Twitter)">
            <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></svg>
          </a>
          <a href="https://www.instagram.com" target="_blank" rel="noopener noreferrer" aria-label="Instagram">
            <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><rect x="2.5" y="2.5" width="19" height="19" rx="5"></rect><circle cx="12" cy="12" r="4.3"></circle><circle cx="17.4" cy="6.6" r="1.1" fill="currentColor" stroke="none"></circle></svg>
          </a>
        </div>
      </div>
    </div>
    <div class="foot__b">
      <span data-year>&copy; 2026 Venture Hub Academy</span>
      <div><a href="#" data-i18n="footer.terms">Terms</a><a href="#" data-i18n="footer.privacy">Privacy</a></div>
    </div>
  </div>
</footer>

<script src="{i18n}"></script>
<script src="{net}"></script>
<script src="{main}"></script>
"""


# d3 + topojson power the APAC network canvas. They are injected only into the
# pages that actually draw a map; without them VhaNetwork shows its text
# fallback instead of the map.
MAP_LIBS = """<script src="https://unpkg.com/d3@7.9.0/dist/d3.min.js" integrity="sha384-CjloA8y00+1SDAUkjs099PVfnY2KmDC2BZnws9kh8D/lX1s46w6EPhpXdqMfjK6i" crossorigin="anonymous" defer></script>
<script src="https://unpkg.com/topojson-client@3.1.0/dist/topojson-client.min.js" integrity="sha384-Ukv1p/xTma6P4/2bY5KzWBw+ydSpXmhCMtyciIQVDJ1RmOxtCYNMF1uXT9T63H67" crossorigin="anonymous" defer></script>
"""


def page_url(filename):
    """The public path: a folder's index.html is served as the folder itself,
    so the canonical for blog/index.html is blog/ and for index.html the root."""
    return filename[:-len("index.html")] if filename.endswith("index.html") else filename


def _from_subfolder(html, depth):
    """Point root-relative URLs back up to the site root.

    Every partial is written for a page at the root (href="css/...",
    src="assets/..."), so a page in blog/ prefixes each relative URL with ../
    rather than every partial learning about folders."""
    up = "../" * depth
    skip = re.compile(r"^(?:[a-z][a-z0-9+.-]*:|#|/|\?)", re.I)
    def one(u):
        return u if not u or skip.match(u) else up + u
    html = re.sub(r'\b(href|src)="([^"]*)"', lambda m: '%s="%s"' % (m.group(1), one(m.group(2))), html)
    return re.sub(r'\bsrcset="([^"]*)"', lambda m: 'srcset="%s"' % ", ".join(
        " ".join([one(part.split()[0])] + part.split()[1:]) for part in m.group(1).split(",")), html)


def write(filename, title, desc, body, current, seo_key, extra_head="", extra_js=""):
    """seo_key=None leaves the page out of the locale's seo table - blog posts
    are English-only, and listing them there would make every new post show up
    as untranslated in all five languages."""
    if "data-apac-map" in body:
        extra_head = MAP_LIBS + extra_head
    url = page_url(filename)
    # The generated markup is English; i18n.js swaps it in place on load when
    # ?lang= names another language, and rewrites internal links to carry it.
    # i18n.js assigns these with document.title = ... and setAttribute, neither
    # of which decodes entities: "&mdash;" would reach the tab as six literal
    # characters. The markup keeps its entities; the locale gets plain text.
    if seo_key:
        SEO[seo_key] = {"title": unescape(title), "description": unescape(desc)}
    # Held on window so the map can wait for it before painting its labels.
    init = ('<script>window.VhaI18nReady = VhaI18n.init(%r)'
            '.catch(function (e) { console.error(e); });</script>\n' % (seo_key or "post"))
    html = (head(title, desc, url, extra_head) + chrome(current) + body
            + footer() + extra_js + init + "</body>\n</html>\n")
    if "/" in filename:
        html = _from_subfolder(html, filename.count("/"))
        os.makedirs(os.path.join(ROOT, os.path.dirname(filename)), exist_ok=True)
    with open(os.path.join(ROOT, filename), "w") as f:
        f.write(html)
    return filename, len(html)


# ==========================================================================
# Pages
# ==========================================================================

def page_home():
    body = hero(
        "home",
        "AI Venture Studio &middot; Accelerator &middot; APAC",
        "Build the next generation of <em>AI companies</em>.",
        "<b>Capital. Operators. Infrastructure. APAC Markets.</b><br>Venture Hub Academy helps ambitious founders build, validate and scale AI-driven businesses across APAC.",
        ("Apply to VHA", "apply.html"), ("Explore the Ecosystem", "#ecosystem"),
        "audience-laugh", "Founders and investors sharing a laugh in the audience at a Venture Hub Academy event.",
        "center 58%",
        ["APAC / HONG KONG / 2026", "APPLICATIONS OPEN", "HK &middot; TW &middot; SG &middot; JP &middot; TH &middot; KH"])
    body += PROOF + MARQUEE + """
  <!-- What VHA does -->
  <section class="section mode-purple" id="platform">
    <div class="wrap">
      <p class="eyebrow" data-i18n="home.platform.eyebrow">What VHA does</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:24px" data-i18n-html="home.platform.title">We don&rsquo;t just accelerate startups.<br>We help build them.</h2>
      <p class="body-l muted" data-reveal style="max-width:60ch;margin-bottom:52px" data-i18n="home.platform.lede">VHA brings together the resources required to turn ambitious ideas into scalable businesses &mdash; from experienced operators and strategic capital to AI infrastructure and access to real markets across APAC.</p>

      <div class="pillars">
        <article class="pillar" data-reveal>
          <div class="pillar__i">01</div>
          <h3 class="pillar__name" data-i18n="home.pillars.capital.name">Capital</h3>
          <div class="pillar__v" data-i18n="home.pillars.capital.value">US$150K</div>
          <p class="pillar__d" data-i18n="home.pillars.capital.desc">Invested via SAFE, alongside access to investors and strategic partners.</p>
        </article>
        <article class="pillar" data-reveal data-delay="0.06">
          <div class="pillar__i">02</div>
          <h3 class="pillar__name" data-i18n="home.pillars.operators.name">Operators</h3>
          <div class="pillar__v" data-i18n="home.pillars.operators.value">Hands-on</div>
          <p class="pillar__d" data-i18n="home.pillars.operators.desc">Support from experienced founders, executives and industry leaders who have built in these markets.</p>
        </article>
        <article class="pillar" data-reveal data-delay="0.12">
          <div class="pillar__i">03</div>
          <h3 class="pillar__name" data-i18n="home.pillars.markets.name">Markets</h3>
          <div class="pillar__v" data-i18n="home.pillars.markets.value">6 APAC</div>
          <p class="pillar__d" data-i18n="home.pillars.markets.desc">Access to customers, partners and market-validation opportunities across the region.</p>
        </article>
        <article class="pillar" data-reveal data-delay="0.18">
          <div class="pillar__i">04</div>
          <h3 class="pillar__name" data-i18n="home.pillars.infra.name">Infrastructure</h3>
          <div class="pillar__v" data-i18n="home.pillars.infra.value">HPC / GPU</div>
          <p class="pillar__d" data-i18n="home.pillars.infra.desc">AI computing, technical resources and infrastructure supporting venture development.</p>
        </article>
      </div>
    </div>
  </section>

  <!-- Build / Validate / Scale -->
  <section class="section mode-inst">
    <div class="wrap">
      <p class="eyebrow" data-i18n="home.journey.eyebrow">The journey</p>
      <h2 class="d-m" data-reveal style="max-width:18ch;margin-bottom:20px" data-i18n-html="home.journey.title">Build. Validate. Scale.</h2>
      <p class="body-l muted" data-reveal style="max-width:52ch;margin-bottom:48px" data-i18n="home.journey.lede">From an early venture to a business that can move across markets.</p>
      <div class="journey journey--three">
        <article class="stage" data-reveal>
          <div class="stage__n">01</div>
          <h3 class="stage__t" data-i18n="home.journey.build.title">Build</h3>
          <p class="stage__d" data-i18n="home.journey.build.desc">Develop the product, business model and core team.</p>
          <span class="tag" data-i18n="home.journey.build.tag">Product &middot; Team</span>
        </article>
        <article class="stage" data-reveal data-delay="0.06">
          <div class="stage__n">02</div>
          <h3 class="stage__t" data-i18n="home.journey.validate.title">Validate</h3>
          <p class="stage__d" data-i18n="home.journey.validate.desc">Test the venture with real customers, partners and markets through the APAC Sandbox.</p>
          <span class="tag" data-i18n="home.journey.validate.tag">APAC Sandbox</span>
        </article>
        <article class="stage" data-reveal data-delay="0.12">
          <div class="stage__n">03</div>
          <h3 class="stage__t" data-i18n="home.journey.scale.title">Scale</h3>
          <p class="stage__d" data-i18n="home.journey.scale.desc">Connect validated ventures with capital, strategic partners, infrastructure and broader markets.</p>
          <span class="tag" data-i18n="home.journey.scale.tag">Capital &middot; Partners</span>
        </article>
      </div>
      <p style="margin-top:40px"><a class="tlink" href="accelerator.html" data-internal><span data-i18n="home.journey.link">See the full program</span> <i aria-hidden="true">&rarr;</i></a></p>
    </div>
  </section>

  <!-- APAC Sandbox -->
  <section class="section mode-energy" id="apac">
    <div class="wrap">
      <div class="apac">
        <div>
          <p class="eyebrow" data-i18n="home.sandbox.eyebrow">APAC Sandbox</p>
          <div class="apac__big" data-reveal aria-hidden="true">06</div>
          <h2 class="d-m" data-reveal style="margin-top:12px" data-i18n-html="home.sandbox.title">Build here.<br>Validate everywhere.</h2>
          <p class="body-l muted" data-reveal style="margin-top:20px;max-width:46ch" data-i18n="home.sandbox.lede">The APAC Sandbox gives founders access to real-world market validation opportunities across a growing network of Asian markets &mdash; market access, validation opportunities and regional connections.</p>
          <ul class="markets" data-reveal data-delay="0.1">
            <li><b>HK</b><span data-i18n="markets.hk">Hong Kong</span><span>22.32&deg; N</span></li>
            <li><b>TW</b><span data-i18n="markets.tw">Taiwan</span><span>23.70&deg; N</span></li>
            <li><b>SG</b><span data-i18n="markets.sg">Singapore</span><span>1.29&deg; N</span></li>
            <li><b>JP</b><span data-i18n="markets.jp">Japan</span><span>35.68&deg; N</span></li>
            <li><b>TH</b><span data-i18n="markets.th">Thailand</span><span>13.75&deg; N</span></li>
            <li><b>KH</b><span data-i18n="markets.kh">Cambodia</span><span>11.55&deg; N</span></li>
          </ul>
        </div>
        <div class="map" data-reveal data-delay="0.12">
          <canvas data-apac-map role="img"
                  aria-label="Network map of the Venture Hub Academy APAC Sandbox markets: Hong Kong, Taiwan, Singapore, Japan, Thailand and Cambodia."
                  data-map-unavailable="Interactive map unavailable. Markets: Hong Kong, Taiwan, Singapore, Japan, Thailand, Cambodia."
                  data-i18n-attr="aria-label:home.sandbox.mapLabel;data-map-unavailable:chrome.mapUnavailable"></canvas>
        </div>
      </div>
      <div class="chain" data-reveal>
        <span class="chain__step" data-i18n="home.sandbox.chain.0">MVP</span>
        <span class="chain__arrow" aria-hidden="true">&rarr;</span>
        <span class="chain__step" data-i18n="home.sandbox.chain.1">Pilot</span>
        <span class="chain__arrow" aria-hidden="true">&rarr;</span>
        <span class="chain__step" data-i18n="home.sandbox.chain.2">Customer feedback</span>
        <span class="chain__arrow" aria-hidden="true">&rarr;</span>
        <span class="chain__step" data-i18n="home.sandbox.chain.3">Market validation</span>
        <span class="chain__arrow" aria-hidden="true">&rarr;</span>
        <span class="chain__step chain__step--end" data-i18n="home.sandbox.chain.4">Scale</span>
      </div>
    </div>
  </section>

  <!-- How VHA works -->
  <section class="section mode-purple">
    <div class="wrap">
      <p class="eyebrow" data-i18n="home.how.eyebrow">How VHA works</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:52px" data-i18n-html="home.how.title">Match. Nurture. Connect.</h2>
      <div class="numlist">
        <article class="numitem" data-reveal>
          <div class="numitem__n">01</div>
          <div>
            <h3 class="numitem__t" data-i18n="home.how.match.title">Match</h3>
            <p class="numitem__d" data-i18n="home.how.match.desc">Connect founders with the right operators, mentors, partners, resources and opportunities.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.06">
          <div class="numitem__n">02</div>
          <div>
            <h3 class="numitem__t" data-i18n="home.how.nurture.title">Nurture</h3>
            <p class="numitem__d" data-i18n="home.how.nurture.desc">Support ventures through product development, market validation, business development and execution.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.12">
          <div class="numitem__n">03</div>
          <div>
            <h3 class="numitem__t" data-i18n="home.how.connect.title">Connect</h3>
            <p class="numitem__d" data-i18n="home.how.connect.desc">Create connections to customers, strategic partners, investors and the wider APAC ecosystem.</p>
          </div>
        </article>
      </div>
    </div>
  </section>

  <!-- Who we back -->
  <section class="section mode-inst">
    <div class="wrap">
      <div class="split">
        <div>
          <p class="eyebrow" data-i18n="who.eyebrow">Who we back</p>
          <h2 class="d-m" data-reveal data-i18n-html="who.title">Experienced operators,<br>not idea-stage<br>first-timers.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <p class="body-l muted" data-i18n="who.body">Venture Hub Academy prioritizes experienced operators over first-time, idea-stage founders. We look for teams with an established commercial foundation who are ready to execute &mdash; not validate an idea from zero.</p>
          <div class="compare">
            <div class="compare__box">
              <div class="compare__label" data-i18n="who.notLabel">Not our fit</div>
              <div class="compare__v" data-i18n="who.notValue">Idea-stage first-timers</div>
            </div>
            <div class="compare__box compare__box--yes">
              <div class="compare__label" data-i18n="who.yesLabel">Our fit</div>
              <div class="compare__v" data-i18n="who.yesValue">Experienced operators</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Ecosystem -->
  <section class="section mode-energy" id="ecosystem">
    <div class="wrap">
      <p class="eyebrow" data-i18n="home.eco.eyebrow">Ecosystem</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:48px" data-i18n-html="home.eco.title">Built with the people moving Asia forward.</h2>
      <div class="tiers">
        <article class="tier" data-reveal>
          <div class="tier__n">01</div>
          <h3 class="tier__t" data-i18n="home.eco.founders.title">Founders &amp; Operators</h3>
          <p class="tier__d" data-i18n="home.eco.founders.desc">People who have built and scaled companies in these markets.</p>
          <div class="tier__foot muted" data-i18n="home.eco.founders.foot">The network</div>
        </article>
        <article class="tier" data-reveal data-delay="0.06">
          <div class="tier__n">02</div>
          <h3 class="tier__t" data-i18n="home.eco.investors.title">Investors &amp; Corporates</h3>
          <p class="tier__d" data-i18n="home.eco.investors.desc">Investors, pilot partners and first customers across the region.</p>
          <div class="tier__foot muted" data-i18n="home.eco.investors.foot">The demand side</div>
        </article>
        <article class="tier tier--core" data-reveal data-delay="0.12">
          <div class="tier__n">03</div>
          <h3 class="tier__t" data-i18n="home.eco.researchers.title">Researchers</h3>
          <p class="tier__d" data-i18n="home.eco.researchers.desc">Academic partners including HKU, HKUST and CUHK.</p>
          <div class="tier__foot" data-i18n="home.eco.researchers.foot">Institutional</div>
        </article>
      </div>
    </div>
  </section>
""" + cta()
    return write("index.html",
                 "Venture Hub Academy &mdash; Build the next generation of AI companies",
                 "An AI venture-building ecosystem for ambitious founders across APAC. Capital, operators, infrastructure and market access to build, validate and scale.",
                 body, "index.html", "home")


def page_accelerator():
    body = hero(
        "acc",
        "Accelerator",
        "A 6-month program<br>for <em>execution</em>.",
        "Three months of structured execution, then three months proving it in live APAC markets. US$150K via SAFE, small cohorts, and the compute to build on.",
        ("Apply Now", "apply.html"), ("See the phases", "#phases"),
        "pitch-results", "Two founders presenting the audience vote for the most investable startup.", "center 58%",
        ["3 MONTHS STRUCTURED + 3 MONTHS SANDBOX", "US$150K VIA SAFE", "UP TO 10 COMPANIES PER COHORT"])
    body += PROOF + MARQUEE + """
  <!-- Overview -->
  <section class="section mode-energy">
    <div class="wrap">
      <p class="eyebrow" data-i18n="acc.overview.eyebrow">Program overview</p>
      <h2 class="d-m" data-reveal style="max-width:18ch;margin-bottom:52px" data-i18n-html="acc.overview.title">How the program is built.</h2>
      <div class="numlist">
        <article class="numitem" data-reveal>
          <div class="numitem__n">01</div>
          <div>
            <h3 class="numitem__t" data-i18n="acc.overview.structure.title">Six-month structure</h3>
            <p class="numitem__d" data-i18n="acc.overview.structure.desc">3-month Structured Program followed by a 3-month APAC Sandbox.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.06">
          <div class="numitem__n">02</div>
          <div>
            <h3 class="numitem__t" data-i18n="acc.overview.cohorts.title">Small, focused cohorts</h3>
            <p class="numitem__d" data-i18n="acc.overview.cohorts.desc">Up to 10 companies per cohort, so every team gets real operator time.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.12">
          <div class="numitem__n">03</div>
          <div>
            <h3 class="numitem__t" data-i18n="acc.overview.capital.title">Capital and compute</h3>
            <p class="numitem__d" data-i18n="acc.overview.capital.desc">US$150K via SAFE, plus GPU and compute resources from day one.</p>
          </div>
        </article>
      </div>
    </div>
  </section>

  <!-- Phases -->
  <section class="section mode-purple" id="phases">
    <div class="wrap">
      <p class="eyebrow" data-i18n="acc.phases.eyebrow">The two phases</p>
      <h2 class="d-m" data-reveal style="max-width:18ch;margin-bottom:44px" data-i18n-html="acc.phases.title">Build, then prove it.</h2>

      <div class="phase" data-reveal>
        <div>
          <span class="tag" data-i18n="acc.phases.p1.tag">Months 1&ndash;3</span>
          <h3 class="phase__t" data-i18n="acc.phases.p1.title">Structured Program</h3>
        </div>
        <ul class="phase__list">
          <li data-i18n="acc.phases.p1.items.0">1-on-1 mentoring by experienced founders and operators.</li>
          <li data-i18n="acc.phases.p1.items.1">Corporate structuring support, research direction, and product strategy.</li>
          <li data-i18n="acc.phases.p1.items.2">Startup execution and scaling guidance.</li>
        </ul>
      </div>

      <div class="phase" data-reveal>
        <div>
          <span class="tag" data-i18n="acc.phases.p2.tag">Months 4&ndash;6</span>
          <h3 class="phase__t" data-i18n="acc.phases.p2.title">APAC Sandbox</h3>
        </div>
        <ul class="phase__list">
          <li data-i18n="acc.phases.p2.items.0">Live customer validation across 6 markets: HK, TW, SG, JP, TH, Cambodia.</li>
          <li data-i18n="acc.phases.p2.items.1">Real revenue signals through live sales, partnerships, or LOIs.</li>
          <li data-i18n="acc.phases.p2.items.2">Accelerated traction-building ahead of fundraising.</li>
        </ul>
      </div>
    </div>
  </section>

  <!-- Compute -->
  <section class="section mode-energy">
    <div class="wrap">
      <div class="split">
        <div>
          <p class="eyebrow" data-i18n="acc.compute.eyebrow">Compute</p>
          <h2 class="d-m" data-reveal data-i18n-html="acc.compute.title">HPC and GPU,<br>from day one.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <p class="body-l muted" data-i18n="acc.compute.body">Access to high-performance clusters for model training, evaluation and deployment &mdash; so infrastructure is never the reason a cohort company slows down.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Demo Day -->
  <section class="section mode-inst">
    <div class="wrap">
      <div class="split">
        <div>
          <p class="eyebrow eyebrow--orange" data-i18n="acc.demo.eyebrow">Demo Day</p>
          <h2 class="d-m" data-reveal data-i18n-html="acc.demo.title">Present live metrics.<br>Raise on evidence.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <p class="body-l muted" data-i18n="acc.demo.body">Founders present live metrics to investors and community. Structured investor access and community-driven momentum.</p>
        </div>
      </div>
    </div>
  </section>
""" + APAC + cta()
    return write("accelerator.html",
                 "Accelerator &mdash; Venture Hub Academy",
                 "A 6-month program: 3-month Structured Program plus 3-month APAC Sandbox. US$150K via SAFE, small cohorts, GPU and compute resources.",
                 body, "accelerator.html", "acc")


def page_community():
    body = hero(
        "com",
        "Community",
        "From open forum<br>to <em>core cohort</em>.",
        "Every cohort starts in the community. It is the open door into the network &mdash; founders, operators and builders, meeting before any commitment is made.",
        ("Join the Community", "apply.html"), ("See the program", "accelerator.html"),
        "home-event", "Founders networking at a Venture Hub Academy event in Hong Kong.", "center 30%",
        ["OPEN FORUM", "MEMBERS", "CORE COHORT"])
    body += MARQUEE + """
  <!-- Tiers -->
  <section class="section mode-inst">
    <div class="wrap">
      <p class="eyebrow" data-i18n="com.tiers.eyebrow">How the community works</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:20px" data-i18n-html="com.tiers.title">Three ways in.</h2>
      <p class="body-l muted" data-reveal style="max-width:52ch;margin-bottom:48px" data-i18n="com.tiers.lede">The community narrows as commitment deepens &mdash; from an open forum, to members, to the funded cohort.</p>
      <div class="tiers">
        <article class="tier" data-reveal>
          <div class="tier__n">01</div>
          <h3 class="tier__t" data-i18n="com.tiers.forum.title">Open Forum</h3>
          <p class="tier__d" data-i18n="com.tiers.forum.desc">Open network, discussing startup ideas, early intent surfacing.</p>
          <div class="tier__foot muted" data-i18n="com.tiers.forum.foot">Open to all</div>
        </article>
        <article class="tier" data-reveal data-delay="0.06">
          <div class="tier__n">02</div>
          <h3 class="tier__t" data-i18n="com.tiers.members.title">Members</h3>
          <p class="tier__d" data-i18n="com.tiers.members.desc">Alumni and shortlisted participants, access to exclusive events.</p>
          <div class="tier__foot muted" data-i18n="com.tiers.members.foot">By shortlist</div>
        </article>
        <article class="tier tier--core" data-reveal data-delay="0.12">
          <div class="tier__n">03</div>
          <h3 class="tier__t" data-i18n="com.tiers.core.title">Core Cohort</h3>
          <p class="tier__d" data-i18n="com.tiers.core.desc">Up to 10 selectively chosen teams, with direct funding and network access.</p>
          <div class="tier__foot" data-i18n="com.tiers.core.foot">Funded &middot; US$150K</div>
        </article>
      </div>
    </div>
  </section>

  <!-- Activity -->
  <section class="section mode-energy">
    <div class="wrap">
      <p class="eyebrow" data-i18n="com.activity.eyebrow">Activity</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:48px" data-i18n-html="com.activity.title">Something is always happening.</h2>
      <div class="collage" data-reveal>
        <figure class="c-wide">
          <img src="assets/images/home-event-1920.jpg" alt="Founders networking at a Venture Hub Academy event." data-i18n-attr="alt:com.activity.night.alt" width="1920" height="1280" loading="lazy">
          <figcaption data-i18n="com.activity.night.caption">Community night &middot; Hong Kong</figcaption>
        </figure>
        <figure class="c-tall">
          <img src="assets/images/demo-day-800.jpg" alt="Panel session with investors at a Venture Hub Academy event." data-i18n-attr="alt:com.activity.panel.alt" width="533" height="800" loading="lazy">
          <figcaption data-i18n="com.activity.panel.caption">Investor panel</figcaption>
        </figure>
        <figure>
          <img src="assets/images/community-photo-800.jpg" alt="Audience at a Venture Hub Academy session." data-i18n-attr="alt:com.activity.session.alt" width="533" height="800" loading="lazy">
          <figcaption data-i18n="com.activity.session.caption">Founder session</figcaption>
        </figure>
        <figure>
          <img src="assets/images/about-photo-800.jpg" alt="Operators in discussion at a Venture Hub Academy session." data-i18n-attr="alt:com.activity.operators.alt" width="800" height="533" loading="lazy">
          <figcaption data-i18n="com.activity.operators.caption">Operator discussion</figcaption>
        </figure>
        <figure class="c-tall">
          <img src="assets/images/vc-challenge-800.jpg" alt="The host introducing the judges of the VC Challenge." data-i18n-attr="alt:com.activity.challenge.alt" width="533" height="800" loading="lazy">
          <figcaption data-i18n="com.activity.challenge.caption">VC Challenge</figcaption>
        </figure>
        <figure class="c-tall">
          <img src="assets/images/judges-chat-800.jpg" alt="Two judges talking in the audience between pitches." data-i18n-attr="alt:com.activity.judges.alt" width="533" height="800" loading="lazy">
          <figcaption data-i18n="com.activity.judges.caption">Between pitches</figcaption>
        </figure>
        <figure class="c-tall">
          <img src="assets/images/audience-focus-800.jpg" alt="Audience members listening closely to a pitch." data-i18n-attr="alt:com.activity.focus.alt" width="533" height="800" loading="lazy">
          <figcaption data-i18n="com.activity.focus.caption">In the room</figcaption>
        </figure>
        <figure class="c-tall">
          <img src="assets/images/audience-front-800.jpg" alt="The audience at the Venture Showcase in a University of Hong Kong lecture theatre." data-i18n-attr="alt:com.activity.showcase.alt" width="533" height="800" loading="lazy">
          <figcaption data-i18n="com.activity.showcase.caption">Venture Showcase &middot; HKU</figcaption>
        </figure>
      </div>
    </div>
  </section>

  <!-- Events -->
  <section class="section mode-inst" id="events">
    <div class="wrap">
      <p class="eyebrow eyebrow--orange" data-i18n="com.events.eyebrow">Up next</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:20px" data-i18n-html="com.events.title">Events across the network.</h2>
      <span class="tag tag--pending" data-reveal style="margin-bottom:36px" data-i18n="com.events.pending">Schedule to be confirmed</span>
      <div class="event-list" style="margin-top:8px">
        <div class="event-row">
          <div class="meta" data-i18n="com.events.demo.date">DATE TBC / HKG</div>
          <div><div class="event-row__t" data-i18n="com.events.demo.title">Demo Day</div></div>
          <div class="meta" data-i18n="com.events.demo.city">HONG KONG</div>
        </div>
        <div class="event-row">
          <div class="meta" data-i18n="com.events.dinner.date">DATE TBC / HKG</div>
          <div><div class="event-row__t" data-i18n="com.events.dinner.title">Founder Dinner</div></div>
          <div class="meta" data-i18n="com.events.dinner.city">HONG KONG</div>
        </div>
        <div class="event-row">
          <div class="meta" data-i18n="com.events.infra.date">DATE TBC / SIN</div>
          <div><div class="event-row__t" data-i18n="com.events.infra.title">AI Infrastructure Session</div></div>
          <div class="meta" data-i18n="com.events.infra.city">SINGAPORE</div>
        </div>
        <div class="event-row">
          <div class="meta" data-i18n="com.events.roundtable.date">DATE TBC / TYO</div>
          <div><div class="event-row__t" data-i18n="com.events.roundtable.title">Investor Roundtable</div></div>
          <div class="meta" data-i18n="com.events.roundtable.city">TOKYO</div>
        </div>
      </div>
    </div>
  </section>
""" + cta("Ready to join<br>the network?", "com.cta.title")
    return write("community.html",
                 "Community &mdash; Venture Hub Academy",
                 "From Open Forum to Core Cohort - join the Venture Hub Academy community of founders, operators, and builders across Asia.",
                 body, "community.html", "com")


def page_about():
    body = hero(
        "about",
        "About",
        "Domain expertise,<br>turned into <em>ventures</em>.",
        "Venture Hub Academy builds and scales AI-driven businesses by partnering with experienced operators &mdash; transforming domain expertise into high-growth, technology-enabled ventures.",
        ("Apply Now", "apply.html"), ("See the accelerator", "accelerator.html"),
        "about-photo", "A Venture Hub Academy panel discussion.", "center 40%",
        ["APAC / HONG KONG / 2026", "ACCELERATOR &middot; VENTURE STUDIO", "BACKED BY FIRST FINANCIAL HOLDING"])
    body += MARQUEE + """
  <!-- Who we back -->
  <section class="section mode-inst">
    <div class="wrap">
      <div class="split">
        <div>
          <p class="eyebrow" data-i18n="who.eyebrow">Who we back</p>
          <h2 class="d-m" data-reveal data-i18n-html="who.title">Experienced operators,<br>not idea-stage<br>first-timers.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <p class="body-l muted" data-i18n="who.body">Venture Hub Academy prioritizes experienced operators over first-time, idea-stage founders. We look for teams with an established commercial foundation who are ready to execute &mdash; not validate an idea from zero.</p>
          <div class="compare">
            <div class="compare__box">
              <div class="compare__label" data-i18n="who.notLabel">Not our fit</div>
              <div class="compare__v" data-i18n="who.notValue">Idea-stage first-timers</div>
            </div>
            <div class="compare__box compare__box--yes">
              <div class="compare__label" data-i18n="who.yesLabel">Our fit</div>
              <div class="compare__v" data-i18n="who.yesValue">Experienced operators</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Selection criteria -->
  <section class="section mode-energy">
    <div class="wrap">
      <p class="eyebrow" data-i18n="about.criteria.eyebrow">Selection criteria</p>
      <h2 class="d-m" data-reveal style="max-width:16ch;margin-bottom:52px" data-i18n-html="about.criteria.title">What we look for.</h2>
      <div class="numlist">
        <article class="numitem" data-reveal>
          <div class="numitem__n">01</div>
          <div>
            <h3 class="numitem__t" data-i18n="about.criteria.team.title">Team quality</h3>
            <p class="numitem__d" data-i18n="about.criteria.team.desc">Quality of team / visionaries of an established business.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.06">
          <div class="numitem__n">02</div>
          <div>
            <h3 class="numitem__t" data-i18n="about.criteria.tech.title">Unique technology</h3>
            <p class="numitem__d" data-i18n="about.criteria.tech.desc">Potentially groundbreaking product or service based on unique technologies.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.12">
          <div class="numitem__n">03</div>
          <div>
            <h3 class="numitem__t" data-i18n="about.criteria.commercial.title">Commercial proposition</h3>
            <p class="numitem__d" data-i18n="about.criteria.commercial.desc">Clear, proven commercial proposition with global opportunities.</p>
          </div>
        </article>
      </div>
    </div>
  </section>

  <!-- Two engines -->
  <section class="section mode-inst">
    <div class="wrap">
      <p class="eyebrow" data-i18n="about.engines.eyebrow">Two engines</p>
      <h2 class="d-m" data-reveal style="max-width:20ch;margin-bottom:20px" data-i18n-html="about.engines.title">Back founders. Build companies.</h2>
      <p class="body-l muted" data-reveal style="max-width:54ch;margin-bottom:40px" data-i18n="about.engines.lede">VHA runs an accelerator and a venture studio from the same platform of capital, compute and market access.</p>
      <div class="compare">
        <div class="compare__box">
          <div class="compare__label" data-i18n="about.engines.acc.label">Accelerator</div>
          <div class="compare__v" data-i18n="about.engines.acc.value">We back founders.</div>
          <p class="muted" style="margin-top:12px;font-size:15.5px" data-i18n="about.engines.acc.desc">A 6-month program for execution-ready teams.</p>
          <p style="margin-top:16px"><a class="tlink" href="accelerator.html" data-internal><span data-i18n="about.engines.acc.link">See the program</span> <i aria-hidden="true">&rarr;</i></a></p>
        </div>
        <div class="compare__box compare__box--yes">
          <div class="compare__label" data-i18n="about.engines.studio.label">Venture Studio</div>
          <div class="compare__v" data-i18n="about.engines.studio.value">We build with founders.</div>
          <p class="muted" style="margin-top:12px;font-size:15.5px" data-i18n="about.engines.studio.desc">Companies co-built from thesis to launch.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- How the studio works -->
  <section class="section mode-energy">
    <div class="wrap">
      <p class="eyebrow" data-i18n="about.studio.eyebrow">How the studio works</p>
      <h2 class="d-m" data-reveal style="max-width:18ch;margin-bottom:52px" data-i18n-html="about.studio.title">Thesis to launch.</h2>
      <div class="numlist">
        <article class="numitem" data-reveal>
          <div class="numitem__n">01</div>
          <div>
            <h3 class="numitem__t" data-i18n="about.studio.thesis.title">Thesis</h3>
            <p class="numitem__d" data-i18n="about.studio.thesis.desc">We identify where AI changes the economics of a sector in these markets, and what has to be true for a company to win there.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.06">
          <div class="numitem__n">02</div>
          <div>
            <h3 class="numitem__t" data-i18n="about.studio.build.title">Build</h3>
            <p class="numitem__d" data-i18n="about.studio.build.desc">Prototype on VHA compute, tested against real operators before a company exists.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.12">
          <div class="numitem__n">03</div>
          <div>
            <h3 class="numitem__t" data-i18n="about.studio.incorporate.title">Incorporate</h3>
            <p class="numitem__d" data-i18n="about.studio.incorporate.desc">Founding team, entity, cap table and jurisdiction &mdash; structured for the markets the company will sell into.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.18">
          <div class="numitem__n">04</div>
          <div>
            <h3 class="numitem__t" data-i18n="about.studio.scale.title">Scale</h3>
            <p class="numitem__d" data-i18n="about.studio.scale.desc">First customers through the APAC Sandbox, then into the accelerator cohort and the raise.</p>
          </div>
        </article>
      </div>
    </div>
  </section>

  <!-- Backing -->
  <section class="section mode-purple">
    <div class="wrap">
      <div class="split">
        <div>
          <p class="eyebrow" data-i18n="about.backing.eyebrow">Institutional backing</p>
          <h2 class="d-m" data-reveal data-i18n-html="about.backing.title">Backed by institutions.</h2>
        </div>
        <div data-reveal data-delay="0.08">
          <div class="backing">
            <div class="backing__box">
              <div class="backing__label" data-i18n="about.backing.financial">Financial</div>
              <div class="backing__v">First Financial Holding</div>
            </div>
            <div class="backing__box">
              <div class="backing__label" data-i18n="about.backing.academic">Academic</div>
              <div class="backing__v">HKU &middot; HKUST &middot; CUHK</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
""" + cta()
    return write("about.html",
                 "About &mdash; Venture Hub Academy",
                 "Venture Hub Academy builds and scales AI-driven businesses by partnering with experienced operators across Asia.",
                 body, "about.html", "about")


APPLY_FORM = open(os.path.join(ROOT, "tools", "apply-form.html")).read() if os.path.exists(
    os.path.join(ROOT, "tools", "apply-form.html")) else ""


def page_apply():
    body = hero(
        "apply",
        "Apply",
        "Fifteen minutes.<br>Read by a <em>partner</em>.",
        "Applications are reviewed on a rolling basis. We respond to every application within 14 days, either way.",
        ("Start application", "#apply-form"), ("See the program", "accelerator.html"),
        "vc-challenge", "The host introducing the judges of the VC Challenge.", "center 45%",
        ["ROLLING BASIS", "RESPONSE WITHIN 14 DAYS", "APPLICATIONS OPEN"])
    body += MARQUEE + """
  <!-- Process -->
  <section class="section mode-inst">
    <div class="wrap">
      <p class="eyebrow" data-i18n="apply.process.eyebrow">The process</p>
      <h2 class="d-m" data-reveal style="max-width:18ch;margin-bottom:52px" data-i18n-html="apply.process.title">Three steps.</h2>
      <div class="numlist">
        <article class="numitem" data-reveal>
          <div class="numitem__n">01</div>
          <div>
            <h3 class="numitem__t" data-i18n="apply.process.application.title">Application</h3>
            <p class="numitem__d" data-i18n="apply.process.application.desc">This form. Reviewed on a rolling basis &mdash; we respond to every application within 14 days.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.06">
          <div class="numitem__n">02</div>
          <div>
            <h3 class="numitem__t" data-i18n="apply.process.interviews.title">Partner interviews</h3>
            <p class="numitem__d" data-i18n="apply.process.interviews.desc">Two conversations, product-deep. With partners, not associates.</p>
          </div>
        </article>
        <article class="numitem" data-reveal data-delay="0.12">
          <div class="numitem__n">03</div>
          <div>
            <h3 class="numitem__t" data-i18n="apply.process.offer.title">Offer</h3>
            <p class="numitem__d" data-i18n="apply.process.offer.desc">US$150K via SAFE on standard terms, and a start date for the next cohort.</p>
          </div>
        </article>
      </div>
    </div>
  </section>
""" + APPLY_FORM
    return write("apply.html",
                 "Apply &mdash; Venture Hub Academy",
                 "Fifteen minutes. Read by a partner. Apply to the Venture Hub Academy accelerator.",
                 body, "apply.html", "apply",
                 extra_js='<script src="%s"></script>\n' % asset("js/vha-apply.js"))


# ==========================================================================
# Blog - posts are Markdown files in posts/, read by tools/blog.py
# ==========================================================================

# Labels that only render in some states (no posts yet, a single post, the
# first or last post). Registered in en.json whatever the state, so the locale
# does not grow and shrink as posts come and go; the templates read the same
# strings.
BLOG_TEXT = {
    "latest": "Latest", "read": "Read the post", "minRead": "min read",
    "earlier": "Earlier posts", "older": "Previous post", "newer": "Next post",
    "all": "All posts", "more": "More posts",
    "empty": {"tag": "First post coming soon",
              "body": "Our first notes on AI, company building and APAC markets are on the way."},
}
T = BLOG_TEXT

RSS_LINK = ('<link rel="alternate" type="application/rss+xml" '
            'title="Venture Hub Academy Blog" href="%sblog/feed.xml">\n' % SITE)


def post_meta(p, author=False):
    """Date and reading time. The date is numeric so it reads the same in
    every language; only "min read" is translated."""
    by = f'\n          <span lang="en">{escape(p["author"])}</span>' if author else ""
    return f"""<div class="meta post-meta">
          <time datetime="{p["date"].isoformat()}">{blog.stamp(p["date"])}</time>
          <span>{p["minutes"]} <span data-i18n="blog.minRead">{T["minRead"]}</span></span>{by}
        </div>"""


def page_blog(posts):
    if posts:
        p = posts[0]
        media = (f'\n        <div class="post-feature__media"><img src="{escape(p["cover"])}" '
                 f'alt="{escape(p["cover_alt"])}" loading="lazy"></div>') if p["cover"] else ""
        listing = f"""
      <a class="post-feature{' post-feature--media' if p['cover'] else ''}" href="{p["file"]}" data-internal data-reveal>{media}
        <div class="post-feature__body">
          <p class="eyebrow" data-i18n="blog.latest">{T["latest"]}</p>
          {post_meta(p)}
          <h2 class="post-feature__t" lang="en">{escape(p["title"])}</h2>
          <p class="body-l muted" lang="en">{escape(p["summary"])}</p>
          <span class="tlink"><span data-i18n="blog.read">{T["read"]}</span> <i aria-hidden="true">&rarr;</i></span>
        </div>
      </a>"""
        if len(posts) > 1:
            rows = "\n".join(f"""        <a class="post-row" href="{q["file"]}" data-internal>
          <time class="meta" datetime="{q["date"].isoformat()}">{blog.stamp(q["date"])}</time>
          <span class="post-row__main">
            <span class="post-row__t" lang="en">{escape(q["title"])}</span>
            <span class="post-row__s" lang="en">{escape(q["summary"])}</span>
          </span>
          <span class="meta post-row__m">{q["minutes"]} <span data-i18n="blog.minRead">{T["minRead"]}</span></span>
        </a>""" for q in posts[1:])
            listing += f"""
      <h2 class="eyebrow eyebrow--orange blog-earlier" data-i18n="blog.earlier">{T["earlier"]}</h2>
      <div class="post-list">
{rows}
      </div>"""
    else:
        listing = f"""
      <div class="blog-empty" data-reveal>
        <span class="tag tag--pending" data-i18n="blog.empty.tag">{T["empty"]["tag"]}</span>
        <p class="body-l muted" data-i18n="blog.empty.body">{T["empty"]["body"]}</p>
      </div>"""

    body = hero(
        "blog",
        "Blog",
        "Our <em>point of view</em> on AI.",
        "Notes from the Venture Hub Academy team on AI, company building and APAC markets &mdash; what we are seeing, and what we think it means for founders.",
        ("Read the posts", "#posts"), ("Apply to VHA", "apply.html"),
        "blog-hero", "Audience members listening closely at a Venture Hub Academy event.", "center 50%",
        ["AI", "COMPANY BUILDING", "APAC MARKETS"])
    body += MARQUEE + f"""
  <section class="section mode-inst blog-index" id="posts">
    <div class="wrap">
      <div class="blog-bar meta">
        <p class="lang-note" data-i18n="blog.langNote">Posts are published in English.</p>
        <a href="blog/feed.xml" class="blog-rss" data-i18n="blog.rss">RSS feed</a>
      </div>{listing}
    </div>
  </section>
""" + cta()
    # The index lives at blog/index.html, not blog.html: the host drops .html,
    # so blog.html is served as /blog - which collides with the blog/ folder
    # holding the posts and answers 403. As the folder's index it is /blog/.
    return write("blog/index.html",
                 "Blog &mdash; Venture Hub Academy",
                 "Our point of view on AI, company building and APAC markets, from the Venture Hub Academy team.",
                 body, "blog/", "blog", extra_head=RSS_LINK)


def page_post(posts, i):
    p = posts[i]
    newer = posts[i - 1] if i > 0 else None
    older = posts[i + 1] if i + 1 < len(posts) else None
    tags = ""
    if p["tags"]:
        tags = '\n        <div class="post__tags" lang="en">%s</div>' % "".join(
            '<span class="tag">%s</span>' % escape(t) for t in p["tags"])
    cover = ""
    if p["cover"]:
        cover = f"""
    <div class="wrap"><figure class="post__cover"><img src="{escape(p["cover"])}" alt="{escape(p["cover_alt"])}" fetchpriority="high"></figure></div>"""
    def pager(q, key, label, cls):
        if not q:
            return "<span></span>"
        return (f'<a class="post-pager__a {cls}" href="{q["file"]}" data-internal>'
                f'<span class="meta" data-i18n="{key}">{label}</span>'
                f'<span class="post-pager__t" lang="en">{escape(q["title"])}</span></a>')
    body = f"""  <article class="post">
    <header class="post__head">
      <div class="wrap post__col">
        <a href="blog/" class="post__back meta" data-internal>&larr; <span data-i18n="blog.all">{T["all"]}</span></a>
        {post_meta(p, author=True)}
        <h1 class="post__title" lang="en">{escape(p["title"])}</h1>
        <p class="body-l post__lede" lang="en">{escape(p["summary"])}</p>{tags}
        <p class="lang-note meta" data-i18n="blog.langNote">Posts are published in English.</p>
      </div>
    </header>{cover}
    <div class="wrap post__col">
      <div class="prose" lang="en">
{p["html"]}
      </div>
      <nav class="post-pager" aria-label="{T["more"]}" data-i18n-attr="aria-label:blog.more">
        {pager(older, "blog.older", T["older"], "post-pager__a--prev")}
        {pager(newer, "blog.newer", T["newer"], "post-pager__a--next")}
      </nav>
    </div>
  </article>
""" + cta()
    return write(p["file"],
                 "%s &mdash; Venture Hub Academy" % escape(p["title"]),
                 escape(p["summary"]),
                 body, "blog/", None, extra_head=RSS_LINK)


def clear_old_posts():
    """A renamed or deleted post must not linger at its old URL."""
    for path in glob.glob(os.path.join(ROOT, "blog", "*.html")):
        with open(path, encoding="utf-8") as f:
            if GENERATED in f.read():
                os.remove(path)


# ==========================================================================
# locales/en.json is derived from the generated markup
# ==========================================================================

# Titles and descriptions are not in the body, so write() records them here.
SEO = {}

# Keys i18n.js needs at runtime that no element carries.
EXTRA_EN = {
    "chrome": {"htmlLang": "en"},
    "nav": {"apply": "Apply", "applyNow": "Apply Now"},
    "blog": BLOG_TEXT,
}


class _LocaleExtractor(HTMLParser):
    """Pull every data-i18n binding out of a generated page.

    en.json is derived rather than hand-written so the two cannot drift: a
    string that changes in the generator changes in the locale on the next
    build, and a key no element references stops being emitted.

    Each open element gets a frame holding its own start tag and a buffer. A
    frame is only folded into its parent when it closes, so the inner HTML a
    key records is exactly what the browser would see as innerHTML."""

    VOID = {"br", "img", "input", "meta", "link", "hr", "source", "area"}

    def __init__(self):
        super().__init__(convert_charrefs=False)
        self.found = {}
        self._stack = []          # [tag, key, buffer, start_tag_text]

    def handle_starttag(self, tag, attrs):
        d = dict(attrs)
        for attr, val in d.items():
            if attr == "data-i18n-attr":
                for pair in val.split(";"):
                    if ":" not in pair:
                        continue
                    target, key = pair.split(":", 1)
                    target, key = target.strip(), key.strip()
                    if target in d:
                        self._record(key, d[target])
        html_key = d.get("data-i18n-html")
        key = html_key or d.get("data-i18n")
        text = self.get_starttag_text()
        if tag in self.VOID:
            if key:
                self._record(key, "")
            self._emit(text)
            return
        self._stack.append([tag, key, [], text, html_key is not None])

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if tag not in self.VOID and self._stack:
            self._stack.pop()

    def handle_endtag(self, tag):
        for i in range(len(self._stack) - 1, -1, -1):
            if self._stack[i][0] == tag:
                # Anything still open inside is unclosed markup; fold it in.
                lost = self._stack[i + 1:]
                del self._stack[i + 1:]
                frame = self._stack.pop()
                inner = "".join(frame[2]) + "".join(
                    f[3] + "".join(f[2]) for f in lost)
                if frame[1]:
                    value = " ".join(inner.split())
                    # A text binding goes through textContent, so "&mdash;"
                    # would reach the page as those eight literal characters.
                    # Decode it here; HTML bindings keep their entities, since
                    # innerHTML parses them.
                    if not frame[4]:
                        value = unescape(value)
                    self._record(frame[1], value)
                self._emit(frame[3] + inner + "</%s>" % tag)
                return

    def _emit(self, chunk):
        if self._stack and chunk:
            self._stack[-1][2].append(chunk)

    def handle_data(self, data):
        self._emit(data)

    def handle_entityref(self, name):
        self._emit("&%s;" % name)

    def handle_charref(self, name):
        self._emit("&#%s;" % name)

    def _record(self, key, value):
        prev = self.found.get(key)
        if prev is not None and prev != value:
            raise SystemExit("locale key %r has two different values:\n  %r\n  %r"
                             % (key, prev, value))
        self.found[key] = value


def _nest(flat):
    out = {}
    for key in sorted(flat):
        node = out
        parts = key.split(".")
        for part in parts[:-1]:
            node = node.setdefault(part, {})
            if not isinstance(node, dict):
                raise SystemExit("locale key %r collides with a shorter key" % key)
        node[parts[-1]] = flat[key]
    return out


def _deep_update(base, extra):
    for k, v in extra.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            _deep_update(base[k], v)
        else:
            base[k] = v
    return base


def build_locale_en(pages):
    flat = {}
    for name in pages:
        ex = _LocaleExtractor()
        with open(os.path.join(ROOT, name), encoding="utf-8") as f:
            ex.feed(f.read())
        for k, v in ex.found.items():
            if k in flat and flat[k] != v:
                raise SystemExit("locale key %r differs between pages:\n  %r\n  %r"
                                 % (k, flat[k], v))
            flat[k] = v
    data = _deep_update(_nest(flat), EXTRA_EN)
    data["seo"] = SEO
    with open(os.path.join(ROOT, "locales", "en.json"), "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)
        f.write("\n")
    return len(flat)


def check_seo(pages):
    """Guard the indexing surface after every build.

    The sitemap, the canonicals and the page list are derived from NAV, so
    they agree by construction - this catches the case where someone later
    hand-edits one of them, and the case where a noindex creeps back onto a
    page (the previous Wix site carried one and stayed out of Google
    entirely)."""
    problems = []

    expected = {SITE + page_url(p) for p in pages}
    with open(os.path.join(ROOT, "sitemap.xml"), encoding="utf-8") as f:
        listed = set(re.findall(r"<loc>([^<]+)</loc>", f.read()))
    if listed != expected:
        problems.append("sitemap URLs %s != built pages %s"
                        % (sorted(listed - expected), sorted(expected - listed)))

    for name in pages:
        with open(os.path.join(ROOT, name), encoding="utf-8") as f:
            html = f.read()
        url = SITE + page_url(name)
        canon = re.findall(r'<link rel="canonical" href="([^"]+)"', html)
        og = re.findall(r'<meta property="og:url" content="([^"]+)"', html)
        if canon != [url]:
            problems.append("%s: canonical %s, expected [%s]" % (name, canon, url))
        if og != [url]:
            problems.append("%s: og:url %s, expected [%s]" % (name, og, url))
        if re.search(r'content="[^"]*noindex', html):
            problems.append("%s: carries a noindex" % name)

    robots = os.path.join(ROOT, "robots.txt")
    if os.path.exists(robots):
        with open(robots, encoding="utf-8") as f:
            text = f.read()
        if ("Sitemap: %ssitemap.xml" % SITE) not in text:
            problems.append("robots.txt does not point at %ssitemap.xml" % SITE)
    else:
        problems.append("robots.txt is missing")

    for row in problems:
        print("    ERROR %s" % row)
    return problems


def build_sitemap(pages, lastmod=None):
    lastmod = lastmod or {}
    prio = {"index.html": ("weekly", "1.0"), "apply.html": ("monthly", "0.9"),
            "blog/index.html": ("daily", "0.8"),
            "accelerator.html": ("monthly", "0.9"), "community.html": ("monthly", "0.8"),
            "about.html": ("monthly", "0.7")}
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">', '']
    for p in pages:
        cf, pr = prio.get(p, ("monthly", "0.6" if p.startswith("blog/") else "0.7"))
        loc = SITE + page_url(p)
        out += ['  <url>', f'    <loc>{loc}</loc>']
        if p in lastmod:
            out.append(f'    <lastmod>{lastmod[p]}</lastmod>')
        out += [f'    <changefreq>{cf}</changefreq>', f'    <priority>{pr}</priority>', '  </url>', '']
    out.append('</urlset>')
    with open(os.path.join(ROOT, "sitemap.xml"), "w") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    posts = blog.load_posts()
    clear_old_posts()
    built = [page_home(), page_accelerator(), page_community(),
             page_about(), page_apply(), page_blog(posts)]
    built += [page_post(posts, i) for i in range(len(posts))]
    for name, size in built:
        print(f"  {name:22} {size:>7,} bytes")
    blog.build_feed(posts, SITE)
    print(f"  {'blog/feed.xml':22} {len(posts)} posts")
    names = [n for n, _ in built]
    build_sitemap(names, {p["file"]: p["date"].isoformat() for p in posts})
    print(f"  {'sitemap.xml':22} rebuilt")
    n_keys = build_locale_en(names)
    print(f"  {'locales/en.json':22} {n_keys:>7,} keys")
    import check_locales
    locale_errors = check_locales.check()[0]
    seo_errors = check_seo(names)
    print(f"  {'seo check':22} {'ok' if not seo_errors else 'FAILED'}")
    if locale_errors or seo_errors:
        sys.exit("build checks failed")
    print(f"\n{len(built)} pages built.")
