#!/usr/bin/env python3
"""Write docs/translation-gaps.md: what each language still needs.

Generated, not hand-written, so it cannot drift from the locale files. Run:

    python3 tools/gap_list.py
"""
import json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import locale_tools as lt

NAMES = {"sc": "Simplified Chinese", "tc": "Traditional Chinese",
         "jp": "Japanese", "th": "Thai", "km": "Khmer"}

# Strings deliberately left in English; they are not gaps.
# Languages whose translations have not had a native-speaker review. A
# complete file is not a finished one: these render in full but every string
# is provisional until a native reviewer signs it off. Remove a language from
# this set only after that review.
PROVISIONAL = {"jp", "th", "km"}

KEEP_ENGLISH_NOTE = """\
Some strings are intentionally not translated and are excluded from the
counts below: the brand name *Venture Hub Academy*, the backer *First
Financial Holding*, the universities *HKU / HKUST / CUHK*, instrument and
hardware names (*SAFE*, *HPC*, *GPU*, *MVP*, *Demo Day*), market codes
(HK/TW/SG/JP/TH/KH), airport codes, the figure *US$150K* and the map
coordinates.
"""


def main():
    en = lt.flat(json.load(open(os.path.join(lt.ROOT, "locales", "en.json"),
                                encoding="utf-8")))
    en = {k: v for k, v in en.items() if isinstance(v, str) and v.strip()}
    out = ["# Translation gaps",
           "",
           "**Audience:** native-speaker translators for Japanese, Thai and Khmer.",
           "",
           "Generated by `tools/gap_list.py` from `locales/*.json`. Every key listed",
           "here currently renders in **English** on the live page, because the",
           "loader layers each language over English and falls back rather than",
           "leaving a blank. Nothing is broken; it is simply not translated yet.",
           "",
           "How to use this: add the key to the language's file in `locales/`, using",
           "the same dotted path. You do not need to add keys you are not",
           "translating. Keys marked **(markup)** contain HTML that must survive:",
           "`<br>` sets a deliberate line break in a display heading and `<em>`",
           "draws the purple highlighter band behind a phrase. Keep those tags,",
           "and move them to wherever the phrase falls in your language.",
           "",
           KEEP_ENGLISH_NOTE]

    for lang in ["jp", "th", "km", "sc", "tc"]:
        tr = lt.flat(lt.load(lang))
        missing = sorted(k for k in en if not str(tr.get(k, "")).strip())
        done = len(en) - len(missing)
        out += ["", "---", "",
                "## %s (`%s.json`)" % (NAMES[lang], lang),
                "",
                "%d of %d strings translated - **%d still in English**."
                % (done, len(en), len(missing))]
        if not missing and lang in PROVISIONAL:
            out += ["", "**PROVISIONAL.** Every string is translated, but none has had a",
                    "native-speaker review. 198 of them were first drafted on 2026-09-21",
                    "to close the English fallback, and the 102 carried over from v1 were",
                    "never checked either. Review the whole file for tone and accuracy",
                    "before treating it as final, then remove `%s` from `PROVISIONAL`"
                    " in `tools/gap_list.py`." % lang, ""]
            continue
        if not missing:
            out += ["", "Complete. Still worth a native-speaker review before launch.", ""]
            continue
        out += ["", "| key | English source |", "| --- | --- |"]
        for k in missing:
            val = en[k].replace("|", "\\|")
            mark = " **(markup)**" if "<" in val else ""
            out.append("| `%s`%s | %s |" % (k, mark, val))
        out.append("")

    out += ["", "---", "", "## Open questions for the native pass", "",
            "1. **Thai and Khmer transliterate two key terms rather than translating",
            "   them:** *Accelerator* is TH `แอคเซลเลอเรเตอร์` / KM `អាចសេឡេរ៉េទ័រ`, and",
            "   *APAC Sandbox* is TH `แซนด์บ็อกซ์เอเชียแปซิฟิก` / KM",
            "   `កម្មវិធីសាកល្បងអាស៊ីប៉ាស៊ីហ្វិក`. Decide whether a native coinage reads better",
            "   to founders in those markets.",
            "2. **\"Operators\"** is JP `オペレーター`, TH `ผู้ประกอบการ` (which also reads",
            "   as \"entrepreneurs\") and KM `ប្រតិបត្តិករ`. SC/TC settled on",
            "   `实战型经营者` / `實戰型經營者`. Confirm each lands as *experienced",
            "   business builders*, not operations staff.",
            "3. **\"Cohort\"** is JP `コホート`, TH `รุ่น`, KM `ជំនាន់`. In SC/TC the tier",
            "   name *Core Cohort* is rendered `入选当期` / `入選當期` (\"selected into the",
            "   cohort\"), since `核心期` is not idiomatic.",
            "4. **Institution names are left in English** (First Financial Holding,",
            "   HKU, HKUST, CUHK). If an official local name exists, supply it.",
            "5. **Japanese, Thai and Khmer have had no native-speaker review at all.**",
            "   See the PROVISIONAL note under each language above.",
            ""]

    path = os.path.join(lt.ROOT, "docs", "translation-gaps.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("wrote", path)


if __name__ == "__main__":
    main()
