#!/usr/bin/env python3
"""Helpers for the locale files.

locales/en.json is generated by build_site.py from the markup. The other five
are hand-maintained and layered over English at runtime, so a file only needs
the keys it actually translates: anything absent falls back to English rather
than rendering blank.
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LANGS = ["sc", "tc", "jp", "th", "km"]


def flat(obj, prefix="", out=None):
    if out is None:
        out = {}
    if isinstance(obj, dict):
        for k, v in obj.items():
            flat(v, f"{prefix}.{k}" if prefix else k, out)
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            flat(v, f"{prefix}.{i}", out)
    else:
        out[prefix] = obj
    return out


def nest(flat_map):
    out = {}
    for key in sorted(flat_map):
        node = out
        parts = key.split(".")
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = flat_map[key]
    return out


def load(lang):
    with open(os.path.join(ROOT, "locales", "%s.json" % lang), encoding="utf-8") as f:
        return json.load(f)


def save(lang, flat_map):
    path = os.path.join(ROOT, "locales", "%s.json" % lang)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(nest(flat_map), f, ensure_ascii=False, indent=2, sort_keys=True)
        f.write("\n")
    return path
